# La perfezione della saggezza

## Introduzione {.unnumbered}

Questo capitolo esamina il ruolo che la saggezza (prajñā) ha all'interno del percorso di sviluppo spirituale del bodhisattva. Per il buddismo, la saggezza (prajñā) -- ovvero la comprensione della vera natura della realtà -- è l'unico strumento valido che ci consente di evitare le insidie sulla via dello sviluppo spirituale. Ma che cosa sia prajñā non è immediatamente evidente e i dibattiti filosofici su questo punto si sono moltiplicati. Nei capitoli otto e none del Bodhicaryāvatāra, le preoccupazioni principalmente pratiche di Śāntideva lasciano dunque il posto a discussioni relative a sottili punti filosofici. Tuttavia, per Śāntideva, la filosofia è posta al servizio della coltivazione dell'intuizione contemplativa: alla fine, le preoccupazioni pratiche e teoriche di Śāntideva risultano essere una cosa sola -- il dibattito filosofico non è mai separato dalle applicazioni pratiche.

## Le due verità

L'argomento del nono capitolo del Bodhicaryāvatāra è, specificamente, la prajñā, termine spesso tradotto "saggezza", "conoscenza superiore" o "discriminazione". In quanto tale, è la "Perfezione della Saggezza" (prajñāpāramitā), l'apice delle sei perfezioni del sentiero del bodhisattva ed è identificata come l'obiettivo dell'insight meditativo (vipaśyanā), lo strumento contemplativo del "vedere attraverso" che, unito alla tranquillità (śamatha), costituisce il cuore della meditazione buddista. Prajñā, come la descrive Śāntideva, corrisponde all'insegnamento della vacuità della tradizione Madhyamaka della filosofia buddista, e deriva da Nāgārjuna. Nāgārjuna è noto per la sua enfasi sulla "vacuità" (śūnyatā) dei fenomeni, ma il significato di questo concetto è stato oggetto di molteplici dibattiti. In questo capitolo cercheremo di chiarire il modo in cui Śāntideva comprende la nozione di śūnyatā.

Il punto di partenza di Śāntideva per introdurre il pensiero Mādhyamika è la classica concezione buddista delle "due verità" (satyadvaya), la verità "relativa" o "superficiale" (saṃvṛti-satya) di come ci appaiono convenzionalmente le cose e la verità "ultima" o "assoluta" (paramārtha-satya), che descrive come stanno veramente le cose.

Śāntideva introduce le due verità come segue:

> Relativo e ultimo,\
> Queste sono dichiarate essere le due verità.\
> L'ultimo non è alla portata dell'intelletto,\
> Poiché si dice che l'intelletto è il relativo.\
> --- (BCA IX:2)

Secondo Prajñākaramati, "Saṃvṛti è così chiamato perché con esso la comprensione di ciò che è così com'è è nascosta, o occlusa... Ignoranza, stupore ed errore sono sinonimi \[di saṃvṛti\]. Poiché l'ignoranza, essendo l'imputazione delle"forme delle cose inesistenti \[a ciò che esiste\] ... è saṃvṛti". Così, per Prajñākaramati "occultamento" ha la precedenza su "convenzionale" come senso primario di saṃvṛti.

La discussione di Prajñākaramati sul significato di ciò che è "ultimo" (paramārtha) rivela una mescolanza di due temi che sono stati associati a questo termine sin dall'antichità. Da un lato, seguendo una tradizione stabilita nell'Abhidharma (cioè, la prima scolastica buddista), "ultimo" è ciò che è in definitiva reale, è ciò che "resiste" a qualsiasi procedura analitica di riduzione. Per Vasubandhu, filosofo del V secolo, questo significa due cose: ciò che è "ultimo" corrisponde agli atomi fisici e/o fenomenici, o dharma, di cui è costituita la realtà (fisica e fenomenica). Per Prajñākaramati pensatore Madhyamika, tuttavia, l'analisi "arrestarsi" davanti a tali "atomi" non ulteriormente riducibili. L'analisi deve continuare fino a rivelare la contingenza radicale di tutti i fenomeni condizionati, ovvero la loro vacuità. In questo secondo senso, il significato di paramārtha corrisponde a "assenza dell'essere intrinseco" di tutti i dharma, ovvero la vacuità.

Il tema di un'analisi che, quando viene spinta agli estremi, non trova un fondamento ultimo, è associato ad un secondo tema, quello del carattere finale, ovvero del fine, del percorso soteriologico: la meta finale è l'"abbandono delle afflizioni". Poiché paramārtha, infatti, può significare, non solo "significato ultimo" in senso analitico, ma anche paramapuruṣārtha, cioè il "termine più alto dell'uomo", ovvero la liberazione (mokṣa) \[dalla sofferenza\].

Nell'interpretazione di Prajñākaramati, dunque, il risultato ultimo dell'analisi dei fenomeni non è solo quello di metterne in luce la necessaria vacuità; è anche quello di illustrare il fatto che il risultato ultimo, o di maggior valore, dell'attività umana è la liberazione delle afflizioni. La liberazione delle afflizioni, dunque, risulta intrinsecamente legata alla comprensione della vacuità dei fenomeni.

<!-- Questa dottrina delle due verità pone però dei problemi a livello logico. È vera a livello della realtà convenzionale, o della verità ultima? Secondo la dottrina Madhyamaka, questa dialettica delle due verità può essere considerata "vera" solo al livello della verità convenzionale: a livello della verità ultima, la verità non può che essere unitaria, e corrisponde alla vacuità (śunyātā). -->

## La liberazione attraverso la vacuità

Per i buddisti indiani, come Śāntideva, la conoscenza non è un fine in se stesso; non è tanto la conoscenza che è in gioco, quanto la riduzione della sofferenza che si dice derivi da tale conoscenza. Il tipo di conoscenza che consente l'eliminazione della sofferenza si chiama prajñā. Questo termine è spesso tradotto come "saggezza", ma sembra essere più vicino al significato di "intuizione", "conoscenza non discriminante" o "apprensione intuitiva". La prajñā è la "conoscenza/saggezza suprema" che consente di raggiungere in modo diretto il risveglio spirituale (bodhi). Tale conseguimento di "conoscenza/saggezza suprema" è frutto, non solo dello studio e della riflessione intellettuale, quanto piuttosto della pratica meditativa.

La prajñā consente di porre fine al "fallimento epistemico", ovvero all'ignoranza (avidyā), che causa la sofferenza.

> Pertanto devono coltivare questa saggezza\
> \[Coloro\] che desiderano porre fine alla sofferenza.\
> --- (BCA IX:1)

Il percorso del bodhisattva conduce all'autentica cognizione della realtà così come veramente è (yathābhūta), ovvero alla visione della vacuità.

::: callout-note
yathābhūta: il modo in cui le cose sono in realtà; un termine usato per designare la vera natura dei fenomeni, la realtà delle cose così come sono in sé stesse prima della loro organizzazione deformata dal nostro pensiero o l'esperienza diretta non mediata dalla sovrapposizione di concetti falsi come l'idea di un'identità o di un sé intrinseco e permanente (ātman). In quanto tale, il termine è usato in Mahāyāna come sinonimo di vacuità (śūnyatā), attualità (tattva), talità o quiddità (tathatā) e così via.
:::

Śāntideva afferma esplicitamente, fin dall'inizio del BCA, che questa gnosi della vacuità, che porta a vedere le cose così come sono, eccede le abilità del nostro intelletto "razionale":

> La realtà ultima non è alla portata dell'intelletto,\
> Perché si dice che il dominio dell'intelletto sia ciò che è relativo.\
> --- (BCA IX:2)

> Il nostro scopo è qui eliminare la causa del dolore:\
> Il pensiero che i fenomeni abbiano una vera esistenza.

Per Śāntideva, dunque, è la reificazione della realtà, ovvero la convinzione che i fenomeni siano dotati di svabhāva, è la causa della sofferenza. Se consideriamo gli enti (bhava) come reali, cioè dotati di un esistenza indipendente, allora naturalmente finiamo per essere attaccati ad essi, anche se essi non sono altro che delle nostre proiezioni, le reificazioni del flusso in continuo cambiamento della nostra esperienza fenomenica.

::: callout-note
Svabhāva significa letteralmente "natura intrinseca", "essere proprio" o "divenire proprio". È la natura intrinseca, la natura essenziale o l'essenza degli esseri e dei fenomeni. Tutte le scuole Mahāyāna rifiutano l'esistenza di una tale natura intrinseca e sostengono che tutti i fenomeni sono privi di qualsiasi tipo di svabhāva. Secondo l'Abhidharma, lo svabhāva era l'unico e inalienabile 'segno' o caratteristica per mezzo del quale le entità potevano essere differenziate e classificate. Identificando lo svabhāva di un'entità si potrebbe produrre una tassonomia degli esistenti reali. Ad esempio, lo svabhāva del fuoco è stato identificato come calore e lo svabhāva dell'acqua è stato definito come fluidità. Così le scuole dell'Hīnayāna, pur negando un sé delle persone, accettarono nondimeno la realtà sostanziale di quegli elementi (dharma) che componevano il mondo in generale, inclusi cinque skandha del soggetto individuale. A partire da Nāgārjuna, il Mādhyamaka mina questo insegnamento negando la realtà sostanziale non solo del sé (ātman) ma di tutti i fenomeni. Tutte le entità sono quindi viste come simili per la mancanza di un modo d'essere discreto o dell'essenza del sé (svabhāva), e per la condivisione invece dell'attributo comune della vacuità (śūnyatā). <!-- Robinson (1957: p. 300) nel discutere la logica di Nāgārjuna, afferma: --> <!-- > Svabhāva è per definizione oggetto di attribuzioni contraddittorie. Se esiste, deve appartenere a un'entità esistente, il che significa che deve essere condizionata, dipendente da altre entità e da cause esterne. Ma svabhāva è per definizione incondizionato, non dipendente da altre entità e non causato. Quindi l'esistenza di svabhāva è impossibile. -->
:::

Secondo Śāntideva, il superamento della reificazione del reale può essere ottenuto solo attraverso la realizzazione della vacuità (śūnyatā), ovvero, con la cessazione del pensiero discorsivo.

> "Siamo liberi", dici, "attraverso la conoscenza delle (Quattro) Verità ---\
> A che serve dunque questa visione del vacuità?"\
> Ma come le stesse scritture hanno proclamato,\
> Senza questo sentiero non ci può essere illuminazione.\
> --- (BCA IX:40)

::: callout-note
Le quattro nobili verità sono:

-   Duḥkha (sofferenza, incapacità di soddisfazione, dolore) è una caratteristica imprescindibile dell'esistenza nel regno del samsara;
-   Samudaya (origine, fonte, combinazione; 'causa'): insieme a Duḥkha viene generata tṛ́ṣṇā ("brama, desiderio o attaccamento, lett."sete"). Mentre tṛ́ṣṇā è tradizionalmente interpretata in occidentale le lingue come la 'causa' di dukkha, tṛ́ṣṇā può anche essere vista come il fattore che ci lega a Duḥkha, o come una risposta a dukkha, che cerca di sfuggirgli;
-   Nirodha (cessazione, fine, riduzione): Duḥkha può essere terminata o contenuta dalla rinuncia o dal lasciar andare questa sete (tṛ́ṣṇā); la riduzione di tṛ́ṣṇā ci libera dal legame di dukkha;
-   Mārga (sentiero, Nobile Ottuplice Sentiero) è il sentiero spirituale che conduce all'eliminazione di tṛ́ṣṇā e Duḥkha.
:::

Si noti che, in questi versi, Śāntideva non introduce śūnyatā mediante una giustificazione di tipo ontologico, ma mediante l'autorità delle Scritture, ovvero, potremmo dire, in termini pragmatici, sottolineandone l'efficacia. In seguito Śāntideva afferma che la mente è, sì, in grado raggiungere momenti di purezza anche senza la realizzazione della vacuità; ma così facendo inevitabilmente finisce per il ricadere nei normali stati di ignoranza; ovvero, senza la realizzazione della vacuità, la mente continua ad oscillare, al di fuori del controllo dell'individuo, tra ignoranza e purezza.

> La mente che non ha realizzato la vacuità,\
> Può essere placata, ma si agiterà nuovamente,\
> Proprio come negli stati meditativi dell'assorbimento non percettivo.\
> Perciò è necessario coltivare la vacuità.\
> --- (BCA IX:48)

In altre parole, Śāntideva afferma che non è sufficiente accontentarsi della capacità di entrare negli stati superiori della coscienza; bisogna anche raggiungere un grado più alto di saggezza (prajñā). Abbiamo visto che prajñā corrisponde alla realizzazione della vacuità, ovvero alla capacità non cadere più vittime dell'abitudine che ci porta ad attribuire un'esistenza intrinseca a quelle che sono solo le nostre proiezioni, ovvero alle categorie. Nelle parole di Nāgārjuna:

> Quando cessa l'ignoranza (avidyā),\
> non sorgono più le formazioni mentali (saṃskāra).\
> --- (MMk. 26.11a)

::: callout-note
Saṃskāra è un concetto complesso, senza una traduzione italiana di una sola parola, che fonde "oggetto e soggetto" come parti interdipendenti della coscienza e del processo epistemologico di ogni essere umano.

La parola significa 'formazioni' o 'ciò che è stato messo insieme', e 'ciò che mette insieme'.

-   Nel primo senso (passivo), saṃskāra si riferisce ai fenomeni condizionati in generale ma specificamente a tutte le "disposizioni" mentali. Queste sono chiamate "formazioni volitive" sia perché si formano come risultato della volizione sia perché sono cause del sorgere di future azioni volitive. Le traduzioni di saṃskāra in questo primo senso della parola includono "cose condizionate", "determinazioni" e "formazioni" (o, in particolare quando ci si riferisce a processi mentali, "formazioni volitive", "costruzioni mentali", "fabbricazioni", "costrutti mentali").
-   Nel secondo senso (attivo) della parola, saṃskāra si riferisce al karma che porta al sorgere condizionato, all'origine dipendente. Le traduzioni di saṃskāra in questo secondo senso della parola includono "condizioni", "fattori condizionati", "cose condizionate", "determinazioni", "formazioni karmiche".

Il termine saṃskāra compare nel Mahāparinibbāna Sutta. Le ultime parole del Buddha, secondo il Mahāparinibbāna Sutta, furono "Discepoli, questo dichiaro: tutte le *cose condizionate* (saṃskāra) sono transienti -- lottate instancabilmente per la vostra liberazione". (Pali: *handa'dāni bhikkhave āmantayāmi vo, vayadhammā saṅkhārā appamādena sampādethā ti.*). Il Buddha insegna dunque che tutti i saṃskāra sono impermanenti (anitya) e privi di essenza. Poiché sono impermanenti non possiamo fare affidamento su di essi. Non comprendere ciò è l'ignoranza (avidyā); la comprensione di questa impermanenza è la saggezza (prajñā).
:::

Śāntideva illustra un duplice beneficio che deriva da prajñā, ovvero dalla realizzazione della vacuità: in primo luogo, prajñā consente di agire con compassione; in secondo luogo, prajñā consente la rimozione delle contaminazioni emotive. Solo la saggezza della vacuità (prajñā) e i "mezzi abili" (upāya) dei bodhisattva consentono di rimuovere completamente le oscurazioni mentali:

> Indugiare e dimorare nel saṃsāra\
> Liberato da ogni brama e da ogni paura\
> Per ottenere il bene di chi soffre a causa dell'ignoranza:\
> Tale è il frutto che la vacuità produce.\
> --- (BCA IX:52)

> Le afflizioni mentali e il velo sulla nostra cognizione ---\
> La cura per tali oscurazioni è la vacuità.\
> --- (BCA IX:54)

> Quindi non è corretto\
> Trovare difetti in questa visione della vacuità.\
> E così, abbandonato ogni dubbio,\
> Dobbiamo meditare sulla vacuità.\
> --- (BCA IX:53)

::: callout-note
Un punto di vista simile, anche se un po' più articolato, che mette in relazione la liberazione dal samsara (mokṣa) con il superamento della dimensione concettuale, è espresso nel Mahayana Uttaratantra Shastra di Arya Maitreya:

> La libertà dall'attaccamento consiste nelle\
> due realtà della cessazione e del sentiero.

Tra le sei qualità che caratterizzano il dharma, le prime tre qualità (essere inconcepibile, libero dal duale e non concettuale) spiegano la *realtà della cessazione*. Pertanto, dovrebbe essere compreso, ci dice Maitreya, che la libertà dall'attaccamento consiste nell'essere inconcepibile, libero dal duale e non concettuale. Le restanti tre qualità (essere puro, rendere manifesto ed essere un fattore riparatore) spiegano la *realtà del sentiero*. Pertanto, la libertà dall'attaccamento corrisponde alla realtà della cessazione; la causa della libertà dall'attaccamento è invece la realtà del sentiero. Insieme, la realtà della cessazione e la realtà del sentiero spiegano che

> il dharma libero dall'attaccamento\
> è caratterizzato dalle due realtà della purificazione.
:::

## La coproduzione condizionata

Per cercare di approfondire la nostra comprensione di śūnyatā, facciamo nuovamente riferimento a Nāgārjuna. Nāgārjuna caratterizza śūnyatā in questo modo:

> Qualunque cosa sia sorta in modo dipendente,\
> la chiamiamo vacuità.\
> --- (MMc. 24,18a)

In altre parole, poiché tutto nasce in dipendenza da cause e condizioni precedenti, non c'è alcunché che possa esistere inerentemente senza la necessità di tali cause e condizioni. Questa mancanza di esistenza intrinseca è, appunto, la "vacuità". La dottrina Mādhyamika, a cui si richiama Śāntideva, presume che tutto, inclusi i nostri stati mentali, sorga in modo dipendente.

Questa è la dottrina della pratītyasamutpāda, ovvero la "coproduzione condizionata", detta anche "originazione interdipendente", o "genesi dipendente", la quale spiega il prodursi dei fenomeni legati all'esistenza secondo una logica di causa ed effetto. Comprendere pratītyasamutpāda e, in parallelo, śūnyatā, significa liberasi dalla reificazione delle nostre proiezioni mentali. E insegnare questa verità ultima, a coloro che continuano a credere alla realtà delle proprie proiezioni mentali, è lo scopo ultimo di Śāntideva:

> Raccoglierò mio patrimonio di meriti,\
> Con riverenza ma libero da qualunque obiettivo concettuale,\
> Quando rivelerò la verità della vacuità\
> A coloro che soffrono credendo nell'esistenza intrinseca delle cose.\
> --- (BCA IX:167)

Ma come si può ottenere l'obiettivo che Śāntideva si pone? Il Bodhicaryāvatāra può essere letto in molti modi.

Secondo Amber Carpenter (2019), il Bodhicaryāvatāra fa parte di quel genere letterario detto *protrèttico* (o protrèptico) \[dal gr. προτρεπτικός, der. di προτρέπω «promuovere, stimolare»\], ovvero un genere letterario le cui opere tendono a esortare, a stimolare. Il Bodhicaryāvatāra ci esorta a trasformare noi stessi in modo tale da giungere ad un nuovo modo di vedere la realtà. Questo ri-orientamento cognitivo non si ottiene, secondo Śāntideva, all'improvviso e tutto in una volta, ma piuttosto si ottiene mediante una lunga pratica, e lo scopo del Bodhicaryāvatāra è proprio quello di guidarci in tale pratica. Per questa ragione, il Bodhicaryāvatāra può essere inteso come un'opera protrèttica. Un modo per leggere il Bodhicaryāvatāra è proprio quello di considerarlo come un manuale di istruzioni per la meditazione. Secondo Śāntideva, infatti, il praticante deve (1) accettare la validità di śūnyatā come un insegnamento del Buddha, e (2) meditare su di essa.

Ricordiamo che il buddismo ha tradizionalmente diviso la pratica della meditazione in due fasi: il calmo dimorare della mente, ovvero la stabilizzazione meditativa (śamatha), e l'insight, intuizione o visione superiore (vipaśyanā). Secondo Śāntideva, neppure gli stadi più avanzati di śamatha sono sufficienti per ottenere la realizzazione della vacuità: è invece necessario alternare stabilizzazione meditativa e meditazione analitica.

<!-- > In solitudine, la mente e il corpo\ -->

<!-- > Non sono turbati dalla distrazione.\ -->

<!-- > Perciò lasciati alle spalle questa vita mondana\ -->

<!-- > E abbandona completamente la distrazione mentale.\ -->

<!-- > --- (BCA VIII:2) -->

> L'insignt unito alla stabilizzazione meditativa\
> Sradica completamente gli stati afflittivi.\
> Sapendo questo, prima cerca śamatha,\
> che deriva dalla gioia di essere liberi dai legami mondani.\
> --- (BCA VIII:4)

Dunque, Śāntideva auspica uno stadio iniziale di rinuncia interiore che consenta alla mente di stabilizzarsi. Ottenuta questa stabilizzazione meditativa, diventa poi possibile iniziare l'analisi della natura della coscienza, ovvero la realizzazione della vacuità. L'oggetto di tale meditazione è la natura illusoria della pseudo-realtà e delle sue cause:

> Le cose, quindi, le quali sono costituite da illusioni,\
> E ciò che deriva dalla forza delle cause:\
> Da dove provengono? Ciò ci dovremmo chiedere.\
> E dove vanno?\
> --- (BCA IX:143)

Il Dalai Lama (1975) riprende l'affermazione di Śāntideva secondo cui la realizzazione della vacuità non può essere ottenuta attraverso il pensiero razionale (l'intelletto). Il Dalai Lama sottolinea che la comprensione della vacuità è un processo a due stadi che, al suo interno, include anche la razionalità del pensiero concettuale. Secondo il Dalai Lama:

> Per ottenere la saggezza non concettuale che realizza la vacuità è necessario prima coltivare una coscienza concettuale della vacuità; solo in seguito al sorgere di una chiara percezione dell'oggetto della meditazione diventa poi possibile giungere ad una conoscenza non concettuale (1975:55).

Analogamente, Śāntideva afferma

> "Non c'è niente" - quando si afferma questo,\
> Non c'è più nulla da esaminare.\
> Come può un "nulla", del tutto non supportato,\
> Dimorare davanti alla mente come un qualcosa di presente?\
> --- (BCA IX:33)

> Quando né l'essere né il non-essere\
> Stanno di fronte alla mente,\
> Non abbiamo altre opzioni:\
> Liberi dai concetti, dimoriamo in un perfetto riposo.\
> --- (BCA IX:34)

Questo processo di "razionalità autocritica" ci porta ad abbandonare gli schemi abituali del pensiero secondo i quali le persone e i fenomeni sono dotati di un'esistenza intrinseca. Questo processo di analisi meditativa analizza l'oggetto della meditazione fino a quando sorge la "cognizione dell'introvabilità". Secondo Śāntideva, giungiamo alla conclusione di questo processo di decostruzione delle nostre abitudini mentali quando non troviamo più nulla da decostruire:

> Ma quando dici, "il processo di analisi\
> diventa, a sua volta, l'oggetto del nostro scrutinio",\
> Anche questa indagine può essere analizzata,\
> E si giunge così ad un'infinita regressione.\
> --- (BCA IX:109)

> Se i fenomeni vengono analizzati fino in fondo,\
> Una tale analisi non produce alcun residuo.\
> Quando l'oggetto viene rimosso, anche il soggetto si placa.\
> In verità si dice che questo sia il nirvāṇa.\
> --- (BCA IX:110)

Raggiunta la "cognizione dell'introvabilità", il meditatore non è in grado di trovare alcun altro "residuo" da chiamare "oggetto", nessun'altra "componente" che possa essere ulteriormente scomposta. Si giunge così al limite dell'analisi meditativa.

Śāntideva nota, tuttavia, che anche quando la vacuità diventa una realizzazione diretta, permane comunque, nel meditatore, un'oscillazione tra questo stadio di realizzazione della vacuità e uno stadio precedente caratterizzato dal pensiero concettuale. Secondo Śāntideva, queste ricadute nella realtà reificata si manifestano fino all'ottavo bhumi del percorso di trasformazione spirituale del bodhisattva. Solo in quello stadio del sentiero il bodhisattva sarà poi in grado di rimanere costantemente, senza altre ricadute, nello stadio di realizzazione diretta della vacuità.

## Che cos'è śūnyatā?

Ma che cos'è la vacuità a cui, Śāntideva ci dice, dobbiamo aspirare?

> Se non c'è validità nella conoscenza discorsiva,\
> Allora tutto ciò che essa presenta è falso.\
> Quindi è illogico meditare su qualunque oggetto della conoscenza,\
> Anche sulla vacuità.\
> --- (BCA IX:138)

> In mancanza di un oggetto per l'analisi,\
> La sua non esistenza non può essere colta.\
> E quindi gli oggetti ingannevoli di qualsiasi tipo\
> Saranno inesistenti in un modo altrettanto ingannevole.\
> --- (BCA IX:139)

In altre parole, è possibile giungere ad una realizzazione della vacuità mediante il pensiero discorsivo che, per sua stessa natura, è ingannevole? O ancora: che cosa si trova quando ci lasciamo alle spalle il pensiero discorsivo? Quando andiamo oltre la verità convenzionale? Quando abbandoniamo le nostre proiezioni mentali? Abbandonando le nostre illusioni è possibile giungere all'Assoluto? A tale domanda, Nāgārjuna, a cui Śāntideva si ispira, fornisce una risposta negativa.

## L'abbandono di tutti i dṛṣṭi

Ma che cos'è dunque śūnyatā? Ovvero, che cos'è quello che si ottiene dopo avere abbandonato le fallacie del pensiero concettuale?

Dire che le cose sono vuote non significa dire che non esistono. Piuttosto, significa dire che non esistono nel modo in cui sembrano, ovvero come entità indipendenti e indipendenti. Dire che le cose sono prive di identità intrinseca significa dire che le cose esistono solo in modo relazionale. Una famosa metafora per illustrare questo è la rete di Indra. Indra è un dio indiano e, come si sarà intuito, possiede una rete enorme. Così enorme, infatti, che si estende all'infinito in tutte le direzioni. Ad ogni nodo della rete c'è un gioiello. Se osserviamo da vicino ciascuno di questi gioielli vediamo, riflessi sulla sua superficie, tutti gli altri gioielli di questa rete infinita. L'aspetto di ogni gioiello, il modo in cui appare, dipende da tutti gli altri gioielli della rete. E questo vale per ciascuno dei gioielli della rete di Indra. Dire che qualcosa è vuoto, significa fare un'affermazione su tutto l'universo, nel passato, presente e futuro.

Un punto importante è che anche la vacuità è priva di essenza, ovvero di un'identità indipendente. La verità che tutto esiste solo in un senso relazionale è anch'essa solo una verità relazionale. La vacuità è essa stessa vuota. In base all'approccio Mādhyamika, la vacuità non è l'Assoluto, non va intesa come l'ennesimo discorso sulla natura delle cose, ma deve invece essere concepita come *uno strumento*. Uno strumento che, man a mano che de-ontologizza, produce il vuoto negli interlocutori privandoli di qualsivoglia appiglio teorico al quale essi possano attaccarsi per continuare a interporre tra sé e il mondo una qualche rappresentazione di senso. La funzione della vacuità è strumentale e decostruente: non serve cioè a produrre una teoria del vuoto, ma a negare ogni contenuto determinato di pensiero in modo tale che il praticante sia poi in grado di cogliere la realtà così com'è (la rete di Indra), al di là dell'attività di proliferazione concettuale (prapañca).

Il discorso sulla vacuità della dottrina Mādhyamika serve quindi solo a vanificare se stesso, non a pervenire ad un Assoluto al di là delle apparenze. L'argomentazione di Nāgārjuna ha l'obiettivo di ottenere un collasso del pensiero discorsivo in virtù dello smarrimento ingenerato dal rifiuto di ogni possibilità predicativa: di qualsivoglia cosa, afferma, non è possibile dire che sia, che non sia, che sia e non sia, che né sia né non-sia (catuṣkoṭi).

Il quadruplice metodo critico di Nāgārjuna si pone l'obiettivo di rendere in-intelleggibile il reale, così come viene rappresentato dal pensiero descrittivo. Ciò che i koṭi di Nāgārjuna esprimono è il tentativo del pensiero discorsivo di costruire una rappresentazione di senso. Ma, in quanto tali, i koṭi di Nāgārjuna costituiscono dei filtri che ci restituiscono la realtà in modo opaco, anziché "così com'è". Nāgārjuna mostra che tutte le possibilità che si possono articolare nell'ambito della pensabilità, ovvero i koṭi, sono contraddittorie. In altri termini, Nāgārjuna mostra come qualsiasi tentativo di appropriazione della realtà per mezzo dei concetti è non tenibile dal punto di vista logico.

In tale contesto, anche śūnyatā viene presentata come un concetto e, in quanto tale, dev'essere respinto (come illustrato dalla precedente citazione del Dalai Lama), altrimenti andrebbe a costituire un ulteriore punto di vista e, anziché assolvere al fine soteriologico di eliminare ogni ostruzione che impedisce di vedere la realtà così com'è, diventerebbe essa stessa un impedimento rispetto all'attingimento diretto della realtà. In tal caso, la vacuità come strumento non condurrebbe all'esperienza del vuoto, ma, perdendo il suo carattere di mezzo e venendo intesa erroneamente come fine, costituirebbe l'ennesimo baluardo di attaccamento mentale. Chi fa dello strumento usato per togliere di mezzo ogni dṛṣṭi (visione del mondo, punto di vista, teoria) l'ennesima dṛṣṭi è detto "incurabile" (asādhya: MMK XIII, 8). Questo effetto viene paragonato a una medicina che, invece di risolvere una malattia, l'accresce.

L'argomentazione dialettica di Nāgārjuna non offre una sintesi che risolva il conflitto tra i diversi punti di vista (dṛṣṭi). Tuttavia si configura come il necessario luogo di transito per potersi elevare alla consapevolezza dell'insufficienza del pensiero discorsivo a cogliere la tathātā: come abbiamo visto in Śāntideva, il pensiero logico-razionale è incapace a cogliere la realtà. È però necessario rendersi conto in maniera diretta e in prima persona di questa incapacità, per potere poi superare il miraggio della razionalità fondativa, e per potere accogliere la realtà così com'è al di fuori della sfera discorsiva. <!-- La ragione che crea punti di vista antitetici e è la stessa ragione che, quando sia divenuta critica, diventa capace di cogliere la tensione tra quei punti di vista. L'elevazione al piano critico si verifica quando si coglie che ogni visione, nel momento in cui si pone, istituisce per ciò stesso una contro-visione che le si oppone in misura uguale e contraria.  --> La dialettica di Nāgārjuna non produce perciò una teoria risolutiva delle antinomie razionali, ma eleva il praticante alla consapevolezza critica del conflitto che la ragione produce in sé stessa.

Nāgārjuna ammette di non avere alcuna tesi propria. La funzione della dialettica che egli mette in campo è puramente negativa, in quanto non opera alcuna sintesi tra le opposte dicotomie. Così, il superamento del conflitto tra i diversi punti di vista non implica una conciliazione concettuale finale, ma il tacitamento della mente e del discorso, *ed è in questo tacitamento che la vacuità si realizza come esperienza concreta anziché come teoria*, che invero è esattamente ciò che impedisce di fare quell'esperienza.

Mostrando l'impossibilità dell'appropriazione concettuale e discorsiva della realtà, Nāgārjuna consegna la vacuità al "nobile silenzio" in cui solo è possibile la pacificazione della mente. <!-- Mostrando l'impossibilità della predicazione, la dialettica mostra l'impossibilità dell'appropriazione concettuale e discorsiva della realtà, e consegna la vacuità non a un discorso, ma al "nobile silenzio", in cui solo è conservata nella sua pienezza e autenticità non-concettuale. Ciò corrisponde alla pacificazione della mente e all'estinzione del pensiero discorsivo che, discriminando, tende all'appropriazione e alimenta il miraggio dell'"io" e del "mio". --> La śūnyatā non deve dunque essere intesa come l'esito di un intenso sforzo cogitativo, ma bensì come l'impossibilità di quella presa che il cogito vorrebbe esercitare nei confronti della realtà. All'ignoranza (avidyā) non subentra quindi una conoscenza teorica, ma l'esperienza diretta della vacuità che il Mahāyāna indica col termine di prajñā-pāramitā (perfezione della saggezza). Non una teoria, dunque, ma la contemplazione.

<!-- Se l'ordinarietà si caratterizza per il continuo tentativo di attuare una presa sul reale, che trova la sua motivazione principale nell'ignoranza (avidyā), l'esperienza della vacuità, per contro, corrisponde al "mollare la presa", poiché essa rivela l'inconsistenza ontologica sia del soggetto, che tale presa agirebbe, sia dell'oggetto, che tale presa subirebbe.  -->

## Il nobile silenzio

Nel Trattato sulla Via di Mezzo (Mūlamadhyamakakārikā), Nāgārjuna afferma che tutto ciò che ha una genesi condizionata è vuoto e che il punto di vista della Via di Mezzo è quello di ritenere tutti i fenomeni come derivanti dalla coproduzione condizionata. In altre parole, Nāgārjuna identifica pratītyasamutpāda (coproduzione condizionata, o originazione interdipendente) con la vacuità: la vacuità non è altro che l'interdipendenza di tutti i fenomeni. Tutto rimanda ad altro proprio perché nulla è in sé fondato, ma ogni cosa è data solo nella sua interconnessione con tutto il resto. In questo continuo rimando ad altro non si trova mai qualcosa che non dipenda da altro che da se stesso: persino saṃsāra e nirvāṇa sono interdipendenti, in quanto ambedue privi di natura propria.

Poiché tutto è vuoto, nulla è afferrabile. Dato che l'esistenza e la costituzione di ogni realtà dipendono da tutto il resto, la separazione ontologica tra "questo" e "quello" corrisponde unicamente al miraggio della sostanza. La sostanza è l'oblio della funzione costitutiva che la relazione ha nei confronti di qualsiasi realtà: non si dà prima un nucleo sostanziale e poi le relazioni che ad esso ineriscono come accidenti, ma ciò che si dà risulta invece proprio dalle relazioni che lo costituiscono. Il fatto che ogni realtà si dia solo in quanto interconnessa con altro vuol dire, appunto, che essa non esiste in sé, in quanto dotata di una propria sostanza, ma può esistere, esiste, muta e infine svanisce solo in quanto dipendente da un vasto insieme di cause e condizioni. Nulla è (esiste) di per sé; tutto è (esiste) solo in virtù della sua interrelazione con altro da sé. Questo è ciò che s'intende con l'espressione "vacuità di natura propria".

La comprensione profonda dell'insegnamento Mahāyāna culmina dunque nell'abbandono dell'insegnamento stesso, in quanto l'insegnamento più elevato diventa quello che si realizza pienamente solo nel silenzio. Dice perciò Nāgārjuna: «Mai, in nessun luogo, nessun Dharma è stato insegnato dal Buddha» (MMK XXV, 24).

La realtà, che risulta dall'estinzione dell'appropriazione concettualmente e dal tacitamento della proliferazione discorsiva (prapañca), non può essere qualificata. Della realtà nulla può essere predicato: né l'essere, né il non-essere, né l'essere e il non-essere, né la negazione di essere e non-essere. Tale "limpida visione", capace di vedere la processualità insostanziale della realtà senza il miraggio ontologico della sostanzialità, è prajñā, ovvero la visione che riconosce la vacuità dei fenomeni. La verità, che consiste in questo disvelamento della realtà così com'è, è data nella forma di una conoscenza esperienziale della vacuità, ovvero come un "conoscere non conoscendo", nel quale svaniscono il soggetto conoscente, l'oggetto conosciuto e l'atto del conoscere.

Il "nobile silenzio" del Buddha può essere indicato come un silenzio "non proposizionale": esso non dice il nirvāṇa, ma è il nirvāṇa; corrisponde, cioè, all'"estinzione" del pensiero ipostatizzante, dell'attaccamento, dell'illusione della sostanzialità, delle idee di "io" e "mio" e di ogni "-ismo", compreso lo stesso Buddh-ismo. Così come il linguaggio, anche il Buddhismo ha infatti valore strumentale: il linguaggio veicola l'insegnamento buddhista, ma sia il linguaggio che l'insegnamento vanno superati; non bisogna attaccarsi ad essi, ma bisogna invece comprenderne il valore terapeutico rispetto alla guarigione dalla malattia costituita dal miscuglio di ignoranza, brama e attaccamento che corrisponde al nostro modo di vivere. Il Buddha stesso, non a caso, affermò la strumentalità del proprio insegnamento paragonandolo a una zattera che, una volta adempiuto al suo scopo, va abbandonata: "Vi ho mostrato, o monaci, come l'insegnamento sia simile a una zattera, la quale è costruita allo scopo di traghettare e non di mantenercisi attaccati".

::: callout-note
Una descrizione della modalità argomentativa di Nāgārjuna è fornita nel testo *Philosophy of Mysticism: Raids on the Ineffable* di Richard H. Jones (2016).

Nāgārjuna giustifica la vacuità attraverso l'eliminazione l'auto-esistenza. Dal momento che rifiuta di avanzare qualsiasi argomento positivo indipendente a sostegno della vacuità, deve rimuovere tutte le possibilità logiche a sostegno dell'auto-esistenza. L'assunzione che sta alla base del metodo argomentativo di Nāgārjuna è che il contrasto tra $x$ e non-$x$ sia esclusivo ed esaustivo. Se assumiamo questo, allora la sua conclusione sulla necessità della vacuità (shunyata) segue come unica alternativa alla negazione dell'auto-esistenza (svabhāva).

Nagarjuna impiega la forma più semplice di inferenza, riconosciuta in Occidente come modus ponens (es. MK 19.6):

(1) Se A, allora B;\
(2) A;\
(3) Pertanto, B.\

Ha anche usato il più complesso modus tollens (ad es. MK 24.24, 27.7):

(1) Se A, allora B;\
(2) Non B;\
(3) Pertanto, non A.\

Ad esempio, se (A) c'è l'auto-esistenza, allora (B) non ci può essere alcun cambiamento (poiché un cambiamento di qualsiasi tipo è impossibile per ciò che è auto-esistente e quindi permanente); ma (non B) vediamo il cambiamento; e quindi, (non A) non c'è auto-esistenza.

Nagarjuna usò anche un'altra forma di inferenza, ovvero

(1) Se A, allora non B.\
(2) Se non-A, allora non-B.\

Il suo punto è che se c'è A o no-A, non c'è B. Ad esempio, se (A) c'è auto-esistenza o (non-A) non c'è, (B) il cambiamento non è possibile: se qualcosa è auto-esistente, è permanente e quindi non può esserci cambiamento; se non c'è auto-esistenza, allora non esiste nulla, e quindi non c'è nulla che possa cambiare.

Nāgārjuna utilizzò anche il metodo delle "quattro opzioni" (catuṣkoṭi). In questo caso, Nāgārjuna nega che $x$ esiste, che $x$ non esiste, che $x$ esiste e non esiste, e che $x$ non esiste né non esiste. Recentemente, è stato mostrato mediante gli strumenti della moderna logica simbolica che le conclusioni di Nāgārjuna sono logicamente valide. Tuttavia, tali letture sono probabilmente ridondanti rispetto al punto che Nāgārjuna ha voluto dimostrare. Nāgārjuna vuole trasmettere il messaggio che non è possibile pensare a nulla in termini di auto-esistenza (svabhāva). Usa l'argomentazione delle quattro opzioni semplicemente per cercare di coprire tutte le possibilità, positive e negative, cioè ci sta dicendo che non ci sono altre opzioni possibili, e quindi non possiamo pensare in alcun modo a nessun fenomeno in termini di "auto-esistenza" (svabhāva). Nāgārjuna vuole esaminare tutte le possibilità in modo tale che tutte le pretese che coinvolgono l'auto-esistenza (svabhāva) vengano eliminate, e quindi la vacuità - cioè l'assenza di qualcosa di auto-esistente - sia stabilita come l'unica alternativa possibile.

È facile dimostrare che l'approccio delle quattro opzioni non è logicamente contraddittorio. Si consideri il fatto che i numeri non hanno colore. Se qualcuno chiede di che colore è il numero 4, potremmo dire "Non è blu, non è un colore diverso dal blu, né blu né un altro colore, né non blu né un altro colore". Tutte e quattro le affermazioni sono vere e coerenti tra loro, poiché i numeri non hanno colore. La negazione di una qualunque delle opzioni non ci impegna logicamente nell'affermare un'altra delle quattro affermazioni sul colore del quattro. Allo stesso modo, con le quattro opzioni riguardanti l'esistenza di qualcosa: per Nāgārjuna, finché pensiamo ai fenomeni in termini di auto-esistenza, non capiamo la vera natura della realtà.

Pensiamo all'esempio di Bertrand Russell "L'attuale re di Francia è calvo". È sbagliato rispondere "sì", o "no", o che "è sia calvo che non calvo", o che "non è né calvo né non calvo", poiché non esiste. Così anche, per Nāgārjuna: solo un'entità dotata realmente di auto-esistenza (svabhāva) potrebbe essere il soggetto delle quattro opzioni, mentre la negazione di tutte e quattro le opzioni è coerente con il fatto che non ci sono realtà auto-esistenti.

In sintesi, gli argomenti di Nāgārjuna sono razionali e logici, anche dal punto di vista di un logico del ventunesimo secolo. Né si può dire che Nāgārjuna stia "usando la ragione per distruggere la ragione": invece cerca di mostrare con un'analisi concettuale rigorosa e con l'uso di un ragionamento logico che qualsiasi sistema metafisico che afferma entità permanenti auto-esistenti è incoerente con ciò che vediamo effettivamente accadere nel mondo e quindi non è tenibile. La logica e la necessità di evitare le contraddizioni sono assolutamente centrali nel modo in cui procedono le sue argomentazioni.

Si noti inoltre che, per quanto si confronti con la logica, il suo scopo è stato soteriologico, ovvero quello di liberare la mente dei non illuminati dal processo di proiezione di concetti sulla realtà fenomenica (prapancha), in modo tale che sia possibile sperimentare la realtà (tattva) del mondo fenomenico così com'è (yathabhutam), liberando così i praticanti dalla sofferenza che tutti noi proviamo quando cerchiamo di costringere la realtà a conformarsi ai nostri preconcetti e ai desideri che ci costringono a vagare nel saṃsāra (devanāgarī संसार, "scorrere insieme").
:::

::: callout-note
Nel buddismo vengono contrapposte forme di conoscenza "non concettuali" (avikalpita) in contrasto con forme di conoscenza che sono "concettuali". Cosa c'è di sbagliato in un concetto? Dharmakirti propone la seguente definizione di concettualizzazione:

> Si parla di concettualizzazione perché appare qualcosa che non è una cosa, ed è un disturbo perché è discordante.

L'idea è che un concetto o una concettualizzazione (vikalpa) è qualcosa che non è una cosa particolare, ma piuttosto un'entità generale o universale (per sua natura, è una categoria). Le entità generali hanno caratteristiche molto diverse dai particolari: non sono limitate nel luogo e nel tempo, non "appaiono" a un soggetto (almeno nello stesso senso in cui le cose possono apparire nella percezione), e sono il risultato di processi di astrazione. In questo senso, i concetti non sono reali nel senso che sono una sorta di finzione risultante da un giudizio che sussume in sé molteplici istanze diverse -- quindi i concetti sono "discordanti" in quanto non corrispondono mai esattamente ad alcun ente particolare. Tuttavia, queste finzioni possono permetterci di comprendere le cose e la realtà, ma solo se non ne veniamo ipnotizzati in modo tale da arrivare a credere che abbiano un valore ontologico maggiore di quello che effettivamente hanno. Questo è un aspetto molto importante del pensiero buddista: le finzioni e persino gli errori possono aiutarci a capire e a progredire verso il "sommo bene", ma solo se non diventiamo prigionieri di essi, solo se li consideriamo strumenti e non obiettivi.
:::

## Relazione tra metafisica e etica

Nel nono capitolo del Bodhicaryāvatāra, Śāntideva si impegna in una lunga difesa della metafisica Madhyamaka contro varie obiezioni, ma senza aggiungere nulla a quanto già affermato da autori precedenti come Nāgārjuna e Candrakīrti. Ciò che invece è maggiormente innovativo dell'approccio di Śāntideva è il modo in cui integra vari argomenti, quali la realizzazione del vacuità (śūnyatā), l'altruismo (anātman) e l'origine dipendente (pratītyasamutpāda), nello sviluppo del percorso spirituale del bodhisattva.

Quale esempio del metodo argomentativo di Śāntideva possiamo considerare un estratto dell'ottavo capitolo, dove Śāntideva fa appello al principio buddista dell'altruismo (anātman) per sostenere che è irrazionale dare priorità al proprio benessere. Questa argomentazione ha suscitato un notevole interesse nel dibattito filosofico contemporaneo.

> Si dovrebbe prima meditare seriamente sull'uguaglianza di se stessi e degli altri\
> in questo modo: "Tutti sperimentano ugualmente sofferenza e felicità,\
> e devo dunque proteggere gli altri come proteggo me stesso".\
> --- (BCA VIII:90)

> Quando la felicità è ugualmente cara agli altri e me stesso,\
> allora cosa c'è di così speciale in me che mi porta a cercare\
> la felicità solo per me stesso?\

> Quando la paura e la sofferenza sono ugualmente ripugnanti agli altri e a me stesso,\
> allora cosa c'è di così speciale in me\
> da portarmi a proteggere me stesso ma non gli altri?\
> --- (BCA VIII:95-96)

Si noti come questi versi possano essere intesi sia come meditazioni progettate per aumentare la nostra compassione, sia come premesse per l'argomentazione di Śāntideva a favore della benevolenza imparziale. Essi agiscono come meditazioni, poiché riflettere sul fatto che il desiderio della felicità e dell'eliminazione della sofferenza degli altri stimola la compassione. Ma nel contempo Śāntideva sfida anche il suo avversario egoistico a fornire una distinzione (viśeṣa) a giustificare l'obiezione che porta ad assegnare una maggiore priorità al proprio benessere rispetto a quello altrui. Poiché il desiderio di libertà dalla sofferenza è lo stesso per tutti, argomenta Śāntideva, il desiderio di eliminare solo la propria sofferenza non può fornire la giustificazione necessaria. Tra le altre possibili obiezioni a sostegno di un comportamento egoistico c'è l'idea che questo particolare dolore appartiene in maniera specifica a me stesso. Śāntideva respinge questa obiezione con tre versi che concludono la sua argomentazione.

> Il continuum di coscienza e l'aggregazione dei suoi costituenti sono irreali.\
> Poiché colui che sperimenta la sofferenza non esiste,\
> a chi appartiene quella sofferenza?\

> Tutte le sofferenze sono senza padrone, senza eccezioni.\
> Dovrebbero essere eliminate semplicemente perché sono sofferenza.\
> Perché in questo caso sono previste delle eccezioni?\

> Perché si dovrebbe prevenire la sofferenza? Perché tutti sono d'accordo.\
> Se la sofferenza deve essere scacciata, allora tutta la sofferenza deve essere scacciata;\
> e se no, allora lo stesso vale per se stessi come per gli altri.\
> --- (BCA VIII:101-103)

Questi versi rispondono a un'obiezione che giustifica l'idea che si debba dare maggiore enfasi al proprio benessere solo perché ci riguarda in prima persona. Śāntideva risponde a questa obiezione egoistica sottolineando che, poiché il sé non esiste (VIII:101), la sofferenza non appartiene a nessuno (VIII:102). Piuttosto, è solo il carattere malevolo e impersonale della sofferenza che deve motivare la sua rimozione. Il verso 103 risponde fornendo un ulteriore obiezione: poiché non ci sono persone, si chiede l'avversario, perché allora eliminare la sofferenza di qualcuno? Śāntideva risponde sottolineando il principio universale che è la sofferenza in sé a dovere essere eliminata, al di là di qualsiasi altra considerazione. Le discussioni devono finire da qualche parte, e l'evidente carattere malevolo della sofferenza è una ragione sufficiente per impegnarsi a rimuoverla. Śāntideva conclude la sua argomentazione affermando che, non essendo stata offerta alcuna giustificativa che assegna un ruolo speciale al sé, è necessario impegnarci a rimuovere la sofferenza di tutti.

Si notino due caratteristiche dell'argomentazione di Śāntideva. In primo luogo, nel Bodhicaryāvatāra Śāntideva propone una stretta connessione tra meditazione e ragionamento filosofico; anche se l'argomentazione filosofica può non essere sufficiente a convincere l'interlocutore, meditare sulla non esistenza del sé e sulla sofferenza degli altri contribuisce a ridurre l'egoismo e a rafforzare la compassione. In secondo luogo, ritroviamo ancora una volta in questi versi di Śāntideva la tensione creativa che si ripropone in altre parti del testo tra il livello convenzionale e il livello ultimo della realtà. A livello convenzionale, si medita sul dolore degli altri e si genera compassione per fornire la motivazione a progredire lungo il sentiero del bodhisattva. Al livello ultimo, si riconosce che il sé non esiste e si usa questa intuizione per dissolvere l'egoismo.

Ciò che è più distintivo nell'approccio di Śāntideva alla saggezza, dunque, non è tanto la sua difesa della prajñā, che si limita a ripetere argomenti già presentati in altre opere, quanto piuttosto l'uso che Śāntideva fa di prajñā quale strumento a sostegno del percorso di trasformazione spirituale del bodhisattva.

## Considerazioni conclusive {.unnumbered}

Sia in India che in Tibet, la presentazione di Śāntideva del sentiero del bodhisattva ha esercitato una grande influenza sullo sviluppo del Buddismo Mahāyāna. Sebbene il BCA sia tutt'altro che esaustivo nel trattamento della dottrina Mahāyāna, lo stile vivace con cui Śāntideva presenta le intuizioni fondamentali del Mahāyāna, hanno reso questo testo un'icona della letteratura buddista. Gli ultimi vent'anni hanno visto lo studio accademico dell'etica buddista trasformarsi in un importante sottocampo degli studi buddisti. Il BCA è diventato uno dei testi chiave di questo movimento in via di sviluppo. Nella presente introduzione ho sottolineato alcuni dei contributi fondamentali del testo alla filosofia morale. Ciò include la considerazione di Śāntideva della relazione tra le posizioni metafisiche, in particolare il non sé, e la conclusione normativa dell'impegno per una benevolenza imparziale. Altrettanto importante è il suo atteggiamento nei confronti della saggezza, che viene integrata nelle meditazioni progettate per sviluppare le altre perfezioni. Il suo resoconto della generosità colpisce nella sua interpretazione del dare come inizialmente e principalmente un atteggiamento mentale di non attaccamento. Allo stesso modo, il suo sviluppo della pazienza è notevole nella sua radicalità in quanto mira a eliminare tutta la rabbia e consentire al bodhisattva di sopportare qualsiasi quantità di dolore fisico senza disagio mentale. Infine, lo stesso voto del bodhisattva è straordinario nella sua infinita ampiezza, ma anche nelle tensioni che contiene, in quanto i bodhisattva senza sé fanno voti che impegnano infinite vite per liberare esseri privi di sostanza. Tutti questi argomenti fanno anche parte di un tema ricorrente del testo nel suo insieme: l'affermazione di Śāntideva secondo cui un impegno perfetto e illimitato nell'altruismo è il modo migliore per eliminare le afflizioni mentali che sono la fonte di ogni sofferenza. Per Śāntideva, dunque, l'altruismo e l'interesse personale convergono perfettamente se si combinano lungo il sentiero del bodhisattva.
