# Il Sūtra dell'insegnamento di Vimalakīrti

## Introduzione {.unnumbered}

Vivere una buona vita, una vita sana, spensierata e ben consapevole delle realtà che deve affrontare, dipende dallo sviluppo di determinate capacità. La principale raccomandazione buddista a questo proposito è la coltivazione di determinate abilità/capacità che si possano usare nella vita quotidiana. Tali capacità si basano sulla chiara percezione della situazione in cui ci troviamo e su un costante allenamento mentale che ci aiuta a evitare "i tre veleni" dell'avidità, dell'odio e dell'illusione. La metafora utilizzata dai buddisti per questo modo di vivere è quella di un "percorso" che può essere esplorato da chiunque speri di rispondere alle sfide della vita con maggiore saggezza e abilità.

Sono state presentate molte versioni e riformulazioni del percorso che fornisce ai buddisti guida e direzione. Un testo sacro per i buddisti, il Vimalakīrti Sūtra, offre diverse immagini di percorsi validi e, così facendo, mostra come diversi tipi di persone in diverse circostanze e contesti possono trarre vantaggio dai modi più saggi e abili per affrontare le vicende della vita. In questo capitolo farò riferimento alla lettura di questo Sūtra fornita nel testo *Living skillfully* da Dale S. Wright (2022). Possiamo pensare al Vimalakīrti Sūtra come ad una meditazione su śūnyatā. In tale meditazione, śūnyatā fa sorgere in noi un nuovo atteggiamento mentale. Questo nuovo atteggiamento mentale motiva, non tanto una riflessione astratta, quanto piuttosto una trasformazione della vita quotidiana. In un certo senso, è come se il Vimalakīrti Sūtra ci suggerisse di fare debordare la meditazione su śūnyatā al di fuori dell'intervallo di tempo in cui siamo seduti sul cuscino, in modo tale che questa meditazione sia presente in ogni momento della nostra vita. La meditazione su śūnyatā, anziché limitarsi ad una riflessione razionale, trasforma così le nostre emozioni e le nostre sensazioni consentendo al Dharma di "incarnarsi" (embodiment) nella nostra esperienza concreta.

## L'incarnazione della saggezza

Intesa in questo modo, la saggezza è la capacità di vedere oltre le convenzioni e le abitudini che guidano la nostra vita quotidiana al fine di comprendere noi stessi e il mondo in modo più completo, più perspicace, e senza illusioni egocentriche. Per Vimalakīrti, nel Sūtra, questa comprensione della natura della realtà più completa e più perspicace non è comunque l'intera "saggezza", perché la saggezza non è semplicemente una questione di una più accurata conoscenza concettuale. La saggezza presentata da Vimalakīrti va al di là del livello di comprensione concettuale del mondo per trasformare il nostro modo di essere nel mondo. La saggezza di Vimalakīrti è la capacità di vivere l'esperienza quotidiana in accordo con la vera natura della realtà, ovvero di mettere in atto un nuovo allineamento con la realtà in tutto ciò che si fa.

La trasformazione da una visione "intellettuale" di śūnyatā ad un'interpretazione "operante" (nella vita quotidiana) non è improvvisa, ma è piuttosto un cambiamento graduale che avviene attraverso la pratica quotidiana. Conoscere qualcosa (in senso intellettuale) e la "saggezza" non sono la stessa cosa. La saggezza si manifesta come un modo di vivere in armonia con la realtà che, includendo l'intelletto, lo supera per includere le altre quattro componenti (skandha) della vita umana. In questo senso, l'autentica saggezza è pienamente incarnata.

::: callout-note
Gli skandha ("aggregati") sono: (1) materia, o corpo (rūpa) -- terra, aria, fuoco e acqua; (2) sensazioni o sentimenti (vedanā); (3) percezioni degli oggetti dei sensi (saṃjñā); (4) formazioni mentali (saṃskāra); e (5) consapevolezza o coscienza, degli altri aggregati mentali (vijñāna).
:::

La saggezza è riconoscere la vacuità di tutte le cose e vivere in armonia con questa realizzazione. Vimalakirti insegna che

> la dimora del bodhisattva è un profondo pensiero sul significato della vacuità.

I bodhisattva trovano quindi dimora nella pratica meditativa del "pensiero profondo sul significato della vacuità". La saggezza dunque trova inizio nella riflessione meditativa sulla vacuità. Ma la sua realizzazione è la capacità non solo di immaginare e capire cosa significhi la vacuità, ma anche di attualizzare tale comprensione nella propria vita mediante i "mezzi abili" (o "mezzi o espedienti"; upāya), ovvero mediante la capacità di trovarsi a proprio agio nella vacuità di tutte le cose. I bodhisattva "realizzano" la vacuità incarnarnandone il significato a un livello molto più profondo del livello concettuale, ovvero ad un livello che comprende anche l'alterazione di percezioni, emozioni, motivazioni e autocoscienza.

Nel Sūtra, non importa quale sia l'argomento che viene discusso, Vimalakīrti ripete sempre la stessa cosa, ovvero la necessità di intendere qualunque aspetto della vita attraverso la comprensione della vacuità, ovvero la comprensione che l'esistenza delle cose è impermanente e mutevole, è contingente perché dipendente da altre cose per essere ciò che è, e quindi è senza un'essenza fissa e immutabile. Senza essere permanenti e incondizionate, tutte le cose continuano ad esistere in uno stato di continua trasformazione, sempre connesse in vari modi a tutte le altre cose le quali, esse stesse, sono in continua trasformazione. La natura di tutte le cose è dunque l'assenza di una natura fissa e indipendente, ma questa mancanza è proprio ciò che le rende quello che sono. Questa mancanza non distrugge le cose, ma le presenta nel loro vero aspetto.

La continua meditazione su questo tema è ciò che suscita la saggezza. Questo, pensano i buddisti, è ciò che il Buddha ha scoperto ed è stata proprio questa comprensione a portarlo al risveglio. La conoscenza di come sono le cose in realtà, tuttavia, non è il punto principale del percorso buddista. Il percorso richiede invece una fondamentale trasformazione nel modo in cui le persone vivono la propria vita, un distacco da idee e abitudini che sono radicate nell'avidità, nell'odio e nell'illusione, ovvero l'apertura ad una vita che sia in armonia con la realtà.

L'impermanenza e il "sorgere dipendente" implicano il riconoscimento che una concezione che si vorrebbe definitiva e completa del reale non può essere altro che un'illusione, solo un altro modo di vivere in maniera rigida e dogmatica. Il Buddha e Vimalakīrti ci suggeriscono invece di maturare un distacco ironico da un tale atteggiamento mentale. Ci insegnano a stare attenti a come accettiamo le idee, anche quelle molto buone: saggezza significa riconoscere la finitudine di ogni sapere. Significa lasciarsi andare, rilassare la presa, in modo che, quando arriverà il cambiamento, si avrà a disposizione una flessibilità sufficiente per poterlo accettare e gestire in maniera positiva. Meditare sulla vacuità richiede un certo grado di non attaccamento, non solo nei confronti di tutte le cose, ma anche nei confronti della stessa vacuità. Anche la vacuità è solo un concetto, una maschera, ed è priva di un'identità propria.

Questo è il motivo per cui Vimalakīrti turba i monaci venuti a discutere del Dharma dicendo loro che "il Dharma non è un rifugio sicuro". Aggrapparsi al buddismo, usarlo come scudo contro l'assalto della realtà, un rifugio dalla realtà, è un altro segno dell'attaccamento, dell'avidità ed è un'illusione. L'insegnamento di Vimalakīrti è sicuramente un insegnamento difficile. Esso mina le nostre convinzioni più radicate mostrando che anche gli stessi insegnamenti buddisti possono diventare un'altra fonte di illusione.

Leggiamo un frammento del capitolo 5.

> \[...\] the venerable Śāriputra had this thought: "There is not even a single chair in this house. Where are these disciples and bodhisattvas going to sit?" The Licchavi Vimalakīrti read the thought of the venerable Śāriputra and said, "Reverend Śāriputra, did you come here for the sake of the Dharma? Or did you come here for the sake of a chair?"

> Śāriputra replied, "I came for the sake of the Dharma, not for the sake of a chair." Vimalakīrti continued, "Reverend Śāriputra, he who is interested in the Dharma is not interested even in his own body, much less in a chair. Reverend Śāriputra, he who is interested in the Dharma has no interest in matter, sensation, intellect, motivation, or consciousness. He has no interest in these aggregates, or in the elements, or in the sense-media. Interested in the Dharma, he has no interest in the realm of desire, the realm of pure matter, or the immaterial realm. Interested in the Dharma, he is not interested in attachment to the Buddha, attachment to the Dharma, or attachment to the Saṅgha. Reverend Śāriputra, he who is interested in the Dharma is not interested in recognizing suffering, abandoning its origination, realizing its cessation, or practicing the path. Why? The Dharma is ultimately without formulation and without verbalization. Who verbalizes: 'Suffering should be recognized, origination should be eliminated, cessation should be realized, the path should be practiced,' is not interested in the Dharma but is interested in verbalization."

> "Reverend Śāriputra, the Dharma is calm and peaceful. Those who are engaged in production and destruction are not interested in the Dharma, are not interested in solitude, but are interested in production and destruction."

> "Furthermore, reverend Śāriputra, the Dharma is without taint and free of defilement. He who is attached to anything, even to liberation, is not interested in the Dharma but is interested in the taint of desire. The Dharma is not an object. He who pursues objects is not interested in the Dharma but is interested in objects. The Dharma is without acceptance or rejection. He who holds on to things or lets go of things is not interested in the Dharma but is interested in holding and letting go. The Dharma is not a secure refuge. He who enjoys a secure refuge is not interested in the Dharma but is interested in a secure refuge. The Dharma is without sign. He whose consciousness pursues signs is not interested in the Dharma but is interested in signs. The Dharma is not a society. He who seeks to associate with the Dharma is not interested in the Dharma but is interested in association. The Dharma is not a sight, a sound, a category, or an idea. He who is involved in sights, sounds, categories, and ideas is not interested in the Dharma but is interested in sights, sounds, categories, and ideas. Reverend Śāriputra, the Dharma is free of compounded things and uncompounded things. He who adheres to compounded things and uncompounded things is not interested in the Dharma but is interested in adhering to compounded things and uncompounded things."

> "Thereupon, reverend Śāriputra, if you are interested in the Dharma, you should take no interest in anything."

Capitolo 3.

> Then, the Licchavi Vimalakīrti thought to himself, "I am sick, lying on my bed in pain, yet the Tathāgata, the arhat, the perfectly accomplished Buddha, does not consider me or take pity upon me, and sends no one to inquire after my illness."

> The Lord knew this thought in the mind of Vimalakīrti and said to the venerable Śāriputra, "Śāriputra, go to inquire after the illness of the Licchavi Vimalakīrti." Thus addressed, the venerable Śāriputra answered the Buddha, "Lord, I am indeed reluctant to go to ask the Licchavi Vimalakīrti about his illness. Why? I remember one day, when I was sitting at the foot of a tree in the forest, absorbed in contemplation, the Licchavi Vimalakīrti came to the foot of that tree and said to me, 'Reverend Śāriputra, this is not the way to absorb yourself in contemplation. You should absorb yourself in contemplation so that neither body nor mind appear anywhere in the three realms. You should absorb yourself in contemplation in such a way that you can manifest all ordinary behavior without forsaking cessation. You should absorb yourself in contemplation in such a way that you can manifest the nature of an ordinary person without abandoning your cultivated spiritual nature. You should absorb yourself in contemplation so that the mind neither settles within nor moves without toward external forms. You should absorb yourself in contemplation in such a way that the thirty-seven aids to enlightenment are manifest without deviation toward any convictions. You should absorb yourself in contemplation in such a way that you are released in liberation without abandoning the passions that are the province of the world."

> "Reverend Śāriputra, those who absorb themselves in contemplation in such a way are declared by the Lord to be truly absorbed in contemplation." "Lord, when I heard this teaching, I was unable to reply and remained silent. Therefore, I am reluctant to go to ask that good man about his sickness."

> The Buddha then said to the venerable Mahāmaudgalyāyana, "Maudgalyāyana, go to the Licchavi Vimalakīrti to inquire about his illness." Maudgalyāyana replied, "Lord, I am indeed reluctant to go to the Licchavi Vimalakīrti to inquire about his illness. Why? I remember one day when I was teaching the Dharma to the householders in a square in the great city of Vaiśālī, and the Licchavi Vimalakīrti came along and said to me, 'Reverend Maudgalyāyana, that is not the way to teach the Dharma to the householders in their white clothes. The Dharma must be taught according to reality."

> "Reverend Maudgalyāyana, the Dharma is without a living being, because it is free of the dust of living beings. It is selfless, because it is free of the dust of desire. It is lifeless, because it is free of birth and death. It is without a person, because it dispenses with past origins and future destinies."

> "The Dharma is peace and pacification, because it is free of desire. It does not become an object, because it is free of words and letters; it is inexpressible, and it transcends all movement of mind."

> "The Dharma is omnipresent, because it is like infinite space. It is without color, mark, or shape, because it is free of all process. It is without the concept of"mine," because it is free of the habitual notion of possession. It is without ideation, because it is free of mind, thought, or consciousness. It is incomparable, because it has no antithesis. It is without presumption of conditionality, because it does not conform to causes."

> "It permeates evenly all things, because all are included in the ultimate realm.59 It conforms to reality by means of the process of nonconformity. It abides at the reality-limit, for it is utterly without fluctuation. It is immovable, because it is independent of the six objects of sense. It is without coming and going, for it never stands still. It is comprised by voidness, it is remarkable through signlessness, and because of wishlessness it is free of presumption and repudiation. It is without establishment and rejection, without birth or destruction. It is without any fundamental consciousness, transcending the range of eye, ear, nose, tongue, body, and thought. It is without highness and lowness. It abides without movement or activity."

> "Reverend Mahāmaudgalyāyana, how could there be a teaching in regard to such a Dharma? Reverend Mahāmaudgalyāyana, even the expression"to teach the Dharma" is presumptuous, and those who listen to it listen to presumption. Reverend Maudgalyāyana, where there are no presumptuous words, there is no teacher of the Dharma, no one to listen, and no one to understand. It is as if an illusory person were to teach the Dharma to illusory people."

> "Therefore, you should teach the Dharma by keeping your mind on this. You should be adept in regard to the spiritual faculties of living beings. By means of the correct vision of the wisdom-eye, manifesting the great compassion, acknowledging the benevolent activity of the Buddha, purifying your intentions, and understanding the definitive expressions of the Dharma, you should teach the Dharma in order that the continuity of the Three Jewels may never be interrupted."

> "Lord, when Vimalakīrti had discoursed thus, eight hundred householders in the crowd conceived the spirit of unexcelled, perfect enlightenment, and I myself was speechless. Therefore, Lord, I am indeed reluctant to go to this good man to inquire about his illness."

> The Buddha then said to the venerable Mahākāśyapa, "Mahākāśyapa, you go to the Licchavi Vimalakīrti to inquire about his illness."

> "Lord, I am indeed reluctant to go to the Licchavi Vimalakīrti to inquire about his illness. Why? I remember one day, when I was in the street of the poor begging for my food, the Licchavi Vimalakīrti came along and said to me, 'Reverend Mahākāśyapa, to avoid the houses of the wealthy, and to favor the houses of the poor‍---this is partiality in benevolence.63 Reverend Mahākāśyapa, you should dwell on the fact of the equality of things, and you should seek alms with consideration for all living beings at all times. You should beg your food in awareness of the ultimate nonexistence of food. You should seek alms for the sake of eliminating the materialism of others. When you enter a town, you should keep in mind its actual voidness, yet you should proceed through it in order to develop men and women. You should enter homes as if entering the family of the Buddha. You should accept alms by not taking anything. You should see form like a man blind from birth, hear sounds as if they were echoes, smell scents as if they were like wind, experience tastes without any discrimination, touch tangible objects without there being in gnosis any contact, and know things with the consciousness of an illusory creature. That which is without a state of being self and a state of being other does not burn. And what does not burn will not be extinguished."

> "Elder Mahākāśyapa, if, equipoised in the eight liberations without transcending the eight perverse paths, you can enter the sameness of reality by means of the sameness of perversity, and if you can make a gift to all living beings and an offering to all the noble ones and buddhas out of even a single measure of alms, then you yourself may eat. Thus, when you eat, after offering, you should be neither affected by afflictions nor free of afflictions, neither involved in concentration nor free of concentration, neither living in the world nor abiding in liberation. Furthermore, those who give such alms, reverend, have neither great merit nor small merit, neither gain nor loss. They should follow the way of the buddhas, not the way of the disciples. Only in this way, Elder Mahākāśyapa, is the practice of eating by alms meaningful."

> "Lord, when I heard this teaching, I was astonished and thought, 'Reverence to all bodhisattvas! If a lay bodhisattva may be endowed with such eloquence, who is there who would not conceive the spirit of unexcelled, perfect enlightenment?' From that time forth, I no longer recommend the vehicles of the disciples and of the solitary sages but recommend the Mahāyāna. And thus, Lord, I am reluctant to go to this good man to inquire about his illness."

> The Buddha then said to the venerable Subhūti, "Subhūti, go to the Licchavi Vimalakīrti to inquire about his illness". Subhūti replied, "Lord, I am indeed reluctant to go to this good man to inquire about his illness. Why? My Lord, I remember one day, when I went to beg my food at the house of the Licchavi Vimalakīrti in the great city of Vaiśālī, he took my bowl and filled it with some excellent food and said to me, 'Reverend Subhūti, take this food if you understand the sameness of all things through the sameness of material objects, and if you understand the sameness of the qualities of the Buddha through the sameness of all things. Take this food if, without abandoning desire, hatred, and folly, you can avoid association with them; if you can follow the path of the single way without ever disturbing the egoistic views; if, neither conquering ignorance and the craving for existence, nor producing knowledge and liberation, your liberation being the same as the equality of the uninterruptible sins, you are neither liberated nor bound; if you do not see the four noble truths, yet are not one who"has not seen the truth"; if you are also neither "one who has attained fruition," nor "an ordinary person," while not having eliminated the qualities of "an ordinary person"; if you are not a noble one, and not a non-noble one; and if, though you are in the presence of all things, you are free of any notion of "all things."

> "Take this food, reverend Subhūti, if, without seeing the Buddha, hearing the Dharma, or serving the Saṅgha, you undertake the religious life under the six outsider masters ---namely, Purāṇa Kāśyapa, Māskārin Gośāliputra, Saṃjāyin Vairaṭiputra, Kakuda Kātyāyana, Ajita Keśakambala, and Nirgrantha Jñātiputra, and follow the ways they prescribe."

> "Take this food, reverend Subhūti, if, entertaining all false views, you find neither extremes nor middle; if, bound up in the eight adversities, you do not obtain favorable conditions; if, assimilating the passions, you do not attain purification; if the dispassion of all living beings is your dispassion, reverend; if those who make offerings to you are not thereby purified; if those who offer you food, reverend, still fall into the three bad migrations; if you associate with all māras; if you entertain all passions; if the nature of passions is the nature of a reverend; if you have hostile feelings toward all living beings; if you despise all the buddhas; if you criticize all the teachings of the Buddha; if you do not rely on the saṅgha; and finally, if you never enter ultimate liberation."

> "Lord, when I heard these words of the Licchavi Vimalakīrti, I wondered what I should say and what I should do, but I was totally in the dark. Leaving the bowl, I was about to leave the house when the Licchavi Vimalakīrti said to me, 'Reverend Subhūti, do not fear these words, and pick up your bowl. What do you think, reverend Subhūti? If it were an incarnation created by the Tathāgata who spoke thus to you, would you be afraid?'

> I answered, 'No indeed, noble sir!' He then said, 'Reverend Subhūti, the nature of all things is like illusion, like a magical incarnation. So you should not fear them. Why? All words also have that nature, and thus the wise are not attached to words, nor do they fear them. Why? All language does not ultimately exist, except as liberation. The nature of all things is liberation."

## Kṣānti

Lo scopo della pratica è l'illuminazione, ma se ci si aggrappa in modo troppo rigido a una qualsiasi concezione dell'illuminazione, quell'idea e quell'attaccamento finiranno per costituire un ostacolo il raggiungimento dello scopo della pratica. Se ci si aggrappa troppo al Dharma per ottenere una "sicurezza spirituale", fissandolo nella mente come se possedesse una natura intrinseca, considerandolo come una serie di istruzioni da seguire alla lettera, allora questo ci fa precipitare di nuovo in quel mondo illusorio che volevamo abbandonare. Pertanto, Vimalakīrti insegna

> il ripudio di tutte le costruzioni discriminatorie riguardanti l'illuminazione

proprio perché «l'illuminazione è la realizzazione della realtà e sperimentare la «realtà» richiede «di maturare il distacco, liberandosi da ogni atteggiamento abituale». Questa snervante esperienza dell'assenza del fondamento è l'aspetto centrale dell'insegnamento di Vimalakīrti. La capacità di guardare in maniera diretta alla verità della vacuità -- ovvero alla verità dell'impermanenza, dell'assenza di sé immutabile, del fatto che nulla è radicato nel proprio essere -- la capacità di non volersi allontanare a tale esperienza per paura è il segno più chiaro dell'incarnazione della saggezza, è il segno più chiaro del risveglio.

La parola usata nel Vimalakīrti Sūtra per descrivere questo aspetto della saggezza è kṣānti, "tolleranza". Attraverso la difficile pratica della concentrazione e della presenza mentale, meditando sulla vacuità di tutte le cose,

> vincendo così l'abitudine di aggrapparsi ad un fondamento ultimo

come dice il Sūtra, i bodhisattva imparano a *tollerare* la verità della realtà:

> "\[I bodhisattva\] raggiungono la tolleranza intuitiva dell'incomprensibilità ultima e della natura non-nata di tutte le cose.

Il Sūtra immagina dunque un bodhisattva in grado di dimorare con fiducia, libero dalle illusioni delle abitudini mentali, in un mondo mutevole che non è mai completamente afferrabile, un mondo fatto di contingenze, di contraddizioni e di dissonanze. Insieme alla capacità di *tollerare* questa realizzazione, questo bodhisattva è anche in grado di lasciarsi alle spalle tutta quell'ansia repressa che è sempre alla ricerca della sicurezza e della certezza, riuscendo invece ad aprirsi all'incomparabile bellezza di un mondo completamente interdipendente e alla gioia che deriva dalla liberazione in questo lasciarsi andare.

## Śūnyatā e karuṇā

Nella trattazione di śūnyatā, il Sūtra suggerisce di considerare tutti gli esseri viventi

> come 'sogni', 'immagini', 'riflessi della luna nell'acqua', 'echi', 'illusioni' e 'miraggi'.

Ma, alzando la posta in gioco del dialogo, Mañjuśrī lancia una sfida molto difficile a Vimalakīrti chiedendogli

> Se un bodhisattva considera tutti gli esseri viventi in questo modo \[ovvero, come illusioni\], come genera per loro la grande compassione?

Se tutti gli esseri viventi sono illusioni, se la loro esistenza è logicamente impossibile, se sono del tutto irreali, allora perché dovremmo preoccuparsi di loro? Come è possibile generare compassione per loro? Cosa ci dovrebbe ispirerebbe a fare tutto ciò che è in nostro potere per aiutarli a vivere in modo migliore, se dobbiamo pensare a loro come inesistenti?

> "Vimalakirti rispose:"Mañjuśrī, quando un bodhisattva considera tutti gli esseri viventi in questo modo, pensa: 'Proprio come ho realizzato il Dharma, così dovrei insegnarlo agli esseri viventi'. In tal modo, genera l'amore che è un vero rifugio per tutti gli esseri viventi; l'amore che è pacifico perché libero dall'attaccamento; l'amore che non è febbrile, perché libero da passioni; l'amore che si accorda con la realtà perché è lo stesso in tutti e tre i tempi; l'amore che è senza conflitto perché libero dalla violenza delle passioni; l'amore che non è duale perché non ha a che fare né con l'esterno né con l'interno; l'amore che è imperturbabile perché è totalmente ultimo.

> "Così genera l'amore che è fermo, infrangibile come un diamante nella sua alta determinazione; l'amore che è puro, purificato nella sua natura intrinseca; l'amore che è pari, a parità di aspirazioni; l'amore dell'arhat che ha eliminato il suo nemico; l'amore del bodhisattva che sostiene sempre gli esseri viventi; l'amore del Tathagata che comprende la realtà; l'amore del Buddha che fa risvegliare gli esseri viventi dal loro sonno; l'amore che è spontaneo perché da sé è completamente illuminato; l'amore che è illuminazione perché è unità di esperienza; l'amore che non ha presunzione perché ha eliminato l'attaccamento e l'avversione; l'amore che è grande compassione perché infonde splendore al Mahāyāna; l'amore che non si esaurisce mai perché riconosce la vacuità e l'altruismo; l'amore che dona il dono del Dharma libero dal pugno stretto di un cattivo insegnante; l'amore che è moralità perché migliora gli esseri viventi immorali; l'amore che è tolleranza perché protegge se stessi e gli altri; l'amore che è fatica perché si assume la responsabilità di tutti gli esseri viventi; l'amore che è contemplazione perché si astiene dall'indulgere nel gusto; l'amore che è saggezza perché provoca il conseguimento al giusto momento; l'amore che è arte liberatrice perché mostra ovunque la via; l'amore che è senza formalità perché puro nella motivazione; l'amore che è senza deviazioni perché agisce in base ad una motivazione decisiva; l'amore che è alta determinazione perché è senza passioni; l'amore che è senza inganno perché non è artificiale; l'amore che è felicità perché introduce gli esseri viventi alla felicità del Buddha. Tale, Mañjuśrī, è il grande amore di un bodhisattva".

Si noti che la risposta di Vimalakīrti elude il punto della domanda di Mañjuśrī descrivendo invece la straordinaria estensione dell'amore che i bodhisattva mostrano per tutti gli esseri viventi, "amore che è pacifico perché libero da attaccamenti, amore che è senza conflitto e violenza", e così via per una pagina intera. Sono immagini profonde di amore, ciascuna degna di contemplazione. Ma non affrontano i punto della domanda di Mañjuśrī: come si può realizzare karuṇā meditando contemporaneamente sul pensiero che "tutti gli esseri sono come sogni, allucinazioni e visioni irreali"? Se gli esseri viventi sono come l'acqua in un miraggio, sembra un errore amarli con tutto il cuore e fare di tutto per assisterli. Potrebbe sembrare che siano lì e abbiano bisogno di aiuto, ma non lo sono e non lo fanno perché sono illusori come l'acqua in un miraggio. Se sono solo illusioni, non meritano il nostro amore.

Per risolvere questa aporia è essenziale tenere presente cosa significa vacuità. Cosa significa dire o pensare che qualcosa è vuoto? La saggezza è vedere la vacuità di tutte le cose, ovvero che tutte le cose sono impermanenti, che pervengono all'esistenza e cambiano in quanto dipendono da numerose condizioni, e che quindi non hanno un'identità intrinseca immutabile, cioè un fondamento statico e indipendente. Mancano di un vero sé nel senso buddista del termine -- come qualcosa che permane immutabile. Quindi, quando il Sūtra afferma che tutti gli esseri viventi sono illusioni, ciò che afferma è il carattere illusorio della loro identità e della loro permanenza immutabile e indipendente. Quando il Sūtra dice che gli esseri viventi non esistono, afferma che ciò che non esiste è il tipo di realtà che i nostro pensiero dualista tipicamente attribuiscono loro: l'idea che siano qualcosa di separato, che può esistere da solo, qualcosa dotato di una "identità intrinseca".

La difficoltà in questi passaggi è che, nel linguaggio buddista, l'idea di "esistenza" implica una realtà sostanziale e incondizionata. Le cose che cambiano e non sono in grado di esistere in isolamento da tutto il resto, sono considerate inesistenti anche se sono proprio di fronte a noi. La vacuità è quindi una caratteristica di tutte le cose, poiché dal punto di vista buddista, nulla rimane per sempre uguale a sé stesso e nulla è completamente indipendente. Questa è una parte importante di ciò che il non-sé significa nel buddismo, e venire a patti con questa realtà fino a utilizzare questa consapevolezza nella nostra vita quotidiana è ciò che la meditazione sulla vacuità intende realizzare. L'ironia di tutto ciò è che, se gli esseri viventi fossero immutabili e indipendenti (come li immaginiamo nelle nostre proiezioni), se avessero un proprio essere indipendente, non potremmo in alcun modo aiutarli, perché sarebbero incapaci di cambiamento.

L'aspetto liberatorio della meditazione sulla vacuità non è solo quello di porci nella condizione di smettere di trattare le persone e le cose come se possedessero un proprio essere immutabile, indipendentemente da cause e condizioni, consentendoci così di accettare il fatto che, necessariamente, muteranno nel tempo e cambieranno in modi che non possiamo anticipare. In aggiunta a ciò, la meditazione sulla vacuità ha un carattere liberatorio nei confronti di noi stessi, ovvero, mettendo in gioco i presupposti radicati che abbiamo su noi stessi e ai quali attribuiamo un'esistenza intrinseca. La meditazione sulla vacuità mette in discussione l'atteggiamento "reificante" che abbiamo nei confronti di noi stessi e che, tra le altre cose, ci porta ad identificarci completamente con i nostri stati d'animo. Ovvero, fa in modo che ci identifichiamo completamente con qualunque cosa attualmente occupi la nostra mente: pensieri, sentimenti, paure, risentimenti e così via. Ci rende vittime di un profondo senso di appartenenza che considera i nostri stati d'animo come se fossero "il sé", che si aggrappa ad ferocemente ad essi, quasi che l'idea di lasciarli andare corrispondesse al distacco dal nostro vero io. Un senso di appartenenza che è ipnotizzato dafli stati mentali effimeri, che si identifica strettamente a ciò che altrimenti sarebbe solo passeggero, come se tali aspetti transienti dei nostri stati d'animo corrispondessero a quello che noi siamo veramente.

Questo punto è presente fin dall'inizio della tradizione buddista. Nell'Anātmalakṣaṇa Sūtra (Discorso sul non-sé), che tradizionalmente è registrato come il secondo discorso pronunciato da Gautama Buddha, il Buddha analizza i costituenti del corpo e della mente di una persona e dimostra che sono tutti impermanenti (anitya), soggetti a sofferenza (duḥkha) e quindi inadatti all'identificazione con un "sé" (ātman):

> Così, monaci, qualsiasi forma, ... sentimento, ... percezione, ... fabbricazioni, ... coscienza di qualunque cosa passata, futura o presente; interna o esterna; palese o sottile; comune o sublime; lontana o vicina: ogni coscienza deve essere vista com'è effettivamente con il giusto discernimento, ovvero come: "Questo non è mio. Questo non è il mio sé. Questo non è quello che sono."

Quando il nostro stato mentale attuale è allettante, attraente, ci aggrappiamo ad esso in una maniera possessiva e ansiosa. Quando proviamo repulsione verso il nostro stato d'animo attuale è come se fossimo respinti da noi stessi, incapaci di sopportare chi siamo veramente. Vimalakīrti chiama questo modo di vivere "vivere nella morsa". "Vivendo in preda a convinzioni dogmatiche, passioni, attaccamenti, risentimenti e dei loro istinti inconsci" entriamo in una forma di schiavitù verso un "dramma" mentale fuori controllo. Identificandoci completamente con questo dramma interiore perdiamo ogni capacità di controllarlo e restiamo permanentemente bloccati in esso.

Di fronte a ciò che viviamo come insopportabile e immutabile cadiamo in una muta depressione. In questo modo accettiamo il risentimento e la disperazione come risultati inevitabili, piuttosto che come prodotti non necessari del nostro auto-assorbimento e del nostro attaccamento. Creiamo così una tragedia auto-ispirata, "un'illusione", dalla quale non riusciamo ad uscire.

In conclusione, possiamo attribuire un duplice significato al termine "illusione" che, nel Sūtra, viene attribuito agli esseri senzienti. Da una parte, l'illusione è ciò di cui sono vittima gli esseri senzienti, quando scambiano le loro proiezioni mentali con qualcosa di "esistente in sé", piuttosto qualcosa che è stato creato ed è transiente; d'altra parte, considerare gli esseri senzienti come "illusioni" significa pensare che non sono necessariamente sempre uguali a sé stessi, ma possono cambiare. È proprio per questa ragione diventa possibile amarli e considerare il loro risveglio da sofferenze inutili come qualcosa che, in definitiva, è importante.
