# Compassione e pensiero non dualistico {#sec-non-dualism}

Come esseri umani, siamo soggetti non solo a illusioni percettive, ma anche cognitive. Un'intuizione centrale del pensiero buddista è che queste illusioni stanno alla radice della sofferenza e che la sofferenza può essere eliminata solo se tali illusioni vengono estirpate. Tra le più pervasive e perniciose di queste illusioni c'è il senso del sé, un'entità dotata di un'identità permanente e separata da quella degli altri enti.

Nel Madhyānta-vibhāga-kārikā (o Versi che distinguono il mezzo e gli estremi) di Maitreya/Asanga [@maitreya2021middle] vengono distinte tre "nature" della realtà. Il pensiero dualistico, ovvero la distinzione tra percipiente e percepito, viene riferito come la natura "dipendente" della realtà, cioè la base o la condizione per il sorgere di una forma di pensiero mistificato o illusorio. Una tale visione reificata delle cose viene definita come la natura "immaginaria" della realtà. Essa include la convinzione dell'esistenza di un sé indipendente e permanente. Infine, la "natura completamente stabilita" di come stanno veramente le cose viene identificata con la vacuità.

La convinzione di un sé sia dotato di caratteristiche di stabilità e permanenza è dunque una distorsione cognitiva, ovvero fa parte di quello che il Madhyānta-vibhāga-kārikā chiama la natura "illusoria" della realtà. Ci possiamo dunque chiedere se sia possibile indebolire questo senso illusorio dell'io, senza però cadere in una visione nichilista ed estrema che ci porterebbe a credere che non esistiamo affatto -- il che implicherebbe l'assenza di un senso di agenzia e, dunque, l'assenza di qualunque responsabilità personale. La risposta della tradizione buddhista è quella ci spinge a vederci come persone, dotate di un forte senso di agenzia e di responsabilità, ma concepite come parte di una totalità molto più ampia, le quali sono, proprio per questa ragione, prive di un'identità "intrinseca", ma vengono invece sempre intese come dipendenti da contingenze e da condizioni. Per il buddhismo, è proprio questo costitutivo aspetto relazionale del sé che consente la compassione.

Leggendo il Bodhicaryāvatāra di Śāntideva abbiamo visto, infatti, come la motivazione "ontologica" della Grande Compassione è l'idea che non vi sia una separazione netta tra gli esseri: essendo privi di natura intrinseca, essendo "śūnya", gli esseri non possono essere "divisi", ovvero separati gli uni dagli altri. Essendo esseri condizionati (saṃskāra), gli individui possono essere concepiti solo come relativi, come enti che possono esistere solo in relazione gli uni con gli altri, ovvero come parti di una totalità. Questa è la ragione per cui "il tuo dolore è anche il mio dolore", ovvero, io sono animato dalla compassione per gli altri.

<!-- L'"indebolimento" dell'io è un aspetto centrale della tradizione Theravāda e viene presentato nel concetto di anātman. In seguito il Mahāyāna ha esteso la negazione di identità intrinseca dal sé a tutti gli enti, mettendo śūnyatā, la vacuità, al centro della sua riflessione filosofica e soteriologica.  -->

Per raggiungere i principali obiettivi buddisti di liberazione e illuminazione suprema è necessario sviluppare due forme di consapevolezza trascendente: una realizzazione diretta dell'inconsistenza della persona (pudgalanairātmyam) e una realizzazione diretta dell'inconsistenza degli enti extra-personali (dharmanairātmyam). Gli oggetti di queste due forme di consapevolezza sono spesso indicati rispettivamente come "la non esistenza di un sé" (anātman) e "la vacuità" (śūnyatā).

Abbiamo visto che la dottrina della Via di Mezzo, Madhyamaka, identifica śūnyatā con pratītyasamutpāda, la co-originazione dipendente. Nella pratītyasamutpāda, il rifiuto di distinguere, al livello della realtà "ultima", tra i diversi fenomeni, significa descrivere la realtà mediante un pensiero non dualistico. Inoltre, il Madhyāntavibhāga ("Distinguere il mezzo e gli estremi") di Maitreya/Asanga afferma che il superamento della "falsa illusione" del pensiero dualistico è proprio quello che viene chiamato "liberazione" (mokṣa; anche affrancamento, emancipazione, salvezza). Infatti, ciò che chiamiamo "esistenza ciclica" non è null'altro che la "concezione illusoria" del pensiero dualistico.

Ma come si sviluppa questa consapevolezza trascendente che conduce a mokṣa? Ovvero, che cosa significa "pensare in maniera non dualistica"? La conoscenza non duale (advayajñāna) si riferisce ad un tipo di conoscenza che è in grado di trascendere la distinzione soggetto/oggetto, la quale governa gli stati convenzionali di coscienza; si riferisce ad un tipo di conoscenza basata che è basata su una consapevolezza che è in grado di rimanere cosciente, senza però richiedere un oggetto della coscienza. In questo capitolo cercheremo di meglio illustrare le caratteristiche del pensiero non dualistico e, per fare questo, esamineremo nuovamente il Vimalakīrti Sūtra.

## Vimalakīrti e la non dualità

La conoscenza non duale è un tema centrale del Vimalakīrti Sūtra (pubblicato da *84000: Translating the Words of the Buddha*). Un capitolo del Sūtra è dedicato esplicitamente a questo tema; ma tutto il Sūtra ci presenta Vimalakīrti, il cui comportamento può essere compreso solo se ci rendiamo conto che le sue scelte e le azioni che Vimalakīrti mette in atto sono motivate da una visione non dualistica del mondo. Secondo Vimalakīrti, infatti, il modo corretto di rapportarsi al mondo è attraverso advayajñāna, ovvero, mediante una consapevolezza non duale. Un titolo alternativo per il Vimalakīrti Sūtra è stato proprio: *Il Sūtra sulla riconciliazione delle dualità*. Il Sūtra caratterizza Vimalakīrti proprio come colui che è in grado di giungere ad una conciliazione degli aspetti diversi del mondo, ovvero, che è capace di mettere al centro l'unità, piuttosto che le differenze.

Ma però si noti che la riconciliazione delle dualità, o differenze, non è la loro cancellazione. Vimalakīrti non si acquieta nella visione dell'unità indifferenziata di tutte le cose. Vimalakīrti vede come tutte le cose si relazionano per formare la totalità, pur rimanendo distinte l'una dall'altra. Vede con grande chiarezza la differenza tra ricchi e poveri, e lavora per superare una tale differenza. Vede la differenza tra chi soffre in modo orribile e chi no, la differenza tra chi affronta le difficoltà con abilità e compostezza e chi non è in grado di farlo. Tutte queste differenze rimangono valide: il non-dualismo di Vimalakīrti non si riduce ad una forma di monismo.

Questo per dire che il mondo in cui vive Vimalakīrti rimane un mondo complesso, disordinato, confuso e in rapido cambiamento, proprio come il nostro mondo. Vimalakīrti non aspira ad un mondo senza differenze, senza tensioni o conflitti; un tale mondo, infatti, sarebbe privo di vita. Mediante la sua pratica, invece, Vimalakīrti fa sorgere in sé l'interesse per questa complessità, un interesse che lo porta a volere essere consapevole di cosa realmente stia accadendo, rimanendo nel contempo saldo nella sua motivazione (vīryapāramitā: "l'entusiasmo di compiere atti virtuosi") e nella sua tolleranza (kṣāntipāramitā).

Nel Sūtra, Vimalakīrti è raffigurato come qualcuno che non si innervosisce e non perde l'equilibrio quando le tensioni aumentano, o quando punti di vista diversi si sfidano a vicenda anche in maniera ruvida. Vimalakīrti è in grado di superare il disagio che tutti noi proviamo in situazioni tese e complicate. Ha coltivato compostezza, flessibilità e resilienza, e fa appello a queste capacità per trasmettere un senso di equilibrio e di speranza agli altri. Il non dualismo di Vimalakīrti è una visione operante, una comprensione esperta del tutto che non viene limitata dalla paura e non vuole escludere nessuno.

A cosa si deve questa compostezza? Che cosa fornisce a Vimalakīrti un supporto o un sostegno che sono sufficienti per consentirgli di intervenire in maniera così abile nella realtà? La risposta del Sūtra è che un tale fondamento è il pensiero non dualistico. Nel Sūtra, un tale modo di pensare conduce all'accettazione dell'opposizione e del conflitto come dimensioni inevitabili della realtà. Percepire le differenze e le tensioni come il tessuto stesso di cui è costituita la nostra vita consente di sviluppare un atteggiamento di equanimità, e rende possibile un lavoro di mediazione sapiente. Rendersi conto di come e perché le cose, che appaiono molto diverse tra loro, in realtà sono parte di un tutto più ampio, consente di affrontare "con abilità" le difficoltà della vita.

Nel Sūtra, Vimalakīrti chiede ai bodhisattva: "cos'è la non dualità?". Ognuno di loro fornisce una risposta molto profonda.

> Quando penso 'io' e 'mio', questa è dualità. Quando 'io' e 'mio' vengono a mancare, questa è non dualità.\

> Dove c'è contaminazione e purificazione, questa è dualità. Quando si va oltre la contaminazione e la purificazione, questa è non dualità.\

> Dove ci sono atti virtuosi e non virtuosi, questa è dualità. Quando si va oltre il virtuoso e il non virtuoso, questa è non dualità.\

> Se pensi che questa sia solo la realtà mondana e che esista un altro mondo più sublime, questa è dualità. Quando vai oltre il mondano e il sublime, questa è non dualità.\

Gli esempi diventano sempre più elaborati e includono spiegazioni relative a tutti i Sei Pāramitā.

> Produzione e distruzione sono due, ma ciò che non è prodotto e non accade non può essere distrutto. Così il raggiungimento della tolleranza (kṣānti) della non-nascita delle cose è l'ingresso nella non dualità.\

::: callout-note
Ricordiamo, come abbiamo visto in precedenza, che

> \[i bodhisattva\] raggiungono la tolleranza intuitiva dell'incomprensibilità ultima e della natura non-nata di tutte le cose.
:::

Inoltre:

> Se desideri la liberazione perché non ti piace il saṃsāra, questa è dualità. L'unico modo in cui puoi realizzare la non dualità è andare oltre il desiderio della liberazione e l'antipatia per il saṃsāra.

Dopo una lunga lista di spiegazioni di cosa sia la non-dualità fornita da trentadue bodhisattva, si arriva a Mañjuśrī, il quale rivolge la sfida stessa al loro ospite, e il capitolo giunge al suo completamento in quello che è stato chiamato il "fragoroso silenzio" di Vimalakīrti. Cioè, alla domanda di Mañjuśrī, Vimalakīrti resta in silenzio. Evocando dunque la non dualità mediante il rifiuto di fare alcuna distinzione -- né affermazioni né negazioni -- Vimalakīrti fornisce una delle più note descrizioni del Dharma nella storia buddhista.

> Quando i bodhisattva ebbero dato le loro spiegazioni, si rivolsero tutti al principe ereditario Mañjuśrī: "Mañjuśrī, qual è l'ingresso del bodhisattva nella nondualità?" Mañjuśrī rispose: "Buoni signori, avete parlato tutti bene. Tuttavia, tutte le vostre spiegazioni sono esse stesse dualistiche. Non conoscere alcun insegnamento, non esprimere nulla, non dire nulla, non spiegare nulla, non annunciare nulla, non indicare nulla e non designare nulla --- questo è l'ingresso nella non dualità.

> Quindi, il principe ereditario Mañjuśrī disse al Licchavi Vimalakīrti: "Tutti abbiamo proposto i nostri insegnamenti, nobile signore. Ora, tu puoi chiarire l'insegnamento dell'ingresso nel principio di non dualità!

> Allora il Licchavi Vimalakīrti mantenne il silenzio, senza dire nulla. Il principe ereditario Mañjuśrī applaudì il Licchavi Vimalakīrti: "Eccellente! Eccellente, nobile signore! Questo è davvero l'ingresso nella non dualità dei bodhisattva. Qui non servono sillabe, suoni e idee".

## Il fragoroso silenzio

Questo è il momento più famoso del sūtra: il momento del silenzio di Vimalakīrti sul tema della non dualità, cioè della realtà ultima.

Fornisco qui due commenti a tale "fragoroso silenzio". Il primo è il commento fornito dai lama e dai traduttori della Khyentse Foundation, che si rifà al punto di vista di Lamotte. Il secondo commento è fornito da Dale S. Wright nel suo testo *Living skillfully*.

Il primo commento nota che, in molte altre occasioni, anziché rimanere in silenzio, Vimalakīrti parla molto della realtà ultima. Il suo silenzio nell'ottavo capitolo produce un forte impatto a causa delle affermazioni che lo precedono, e che culminano nell'affermazione di Mañjuśrī secondo cui il silenzio stesso è la migliore spiegazione della non dualità. Quindi non sempre il silenzio deve essere considerato come l'insegnamento più profondo, ma solo il silenzio che si manifesta nel contesto speciale del pensiero della realtà ultima. Ad esempio, i silenzi dei discepoli nel cap. 3, ovvero i silezi dei discepoli che sono rimasti senza parole di fronte alla critica di Vimalakīrti, non sono considerati profondi; né lo è il silenzio di Śāriputra quando viene interrogato dalla dea nel cap. 6. Candrakīrti ha questo da dire sulla questione se gli illuminati utilizzino o meno argomenti logici (cioè, il pensiero discorsivo, o dualistico): "Chi può dire se i nobili (usano argomenti logici) o no? La realtà ultima è (anche) descritta nel"silenzio dei santi". Che dire dunque della necessità di impiegare o meno il pensiero discorsivo? Come dice la Dea a Śāriputra (6,20):

> ...non cercare la liberazione abbandonando la parola! Come mai? La liberazione è l'uguaglianza di tutte le cose!

Quindi, per seguire l'argomentazione del sūtra potremmo dire che la distinzione tra "silenzio" e "pensiero discorsivo" è dualistica. Se da una parte la parola è in definitiva priva di significato in riferimento alla realtà ultima, d'altra parte il silenzio esiste solo in contrasto con la parola. Invece, come scrive Lamotte (pp 317-318, n. 43) è la comprensione dell'uguaglianza di silenzio e parola che fornisce l'ingresso nella non-dualità.

Nel nono capitolo di *Living skillfully*, Dale S. Wright cerca di articolare il "fragoroso silenzio" di Vimalakīrti. Dale S. Wright ci dice che, mentre la maggior parte di noi lotta con il conflitto tra la tranquillità della nostra pratica meditativa e la nostra esperienza nella vita quotidiana, Vimalakīrti sperimenta insieme queste due esperienze, indagando la loro non dualità. Vede che la trasformazione personale è resa possibile dal cambiamento storico collettivo e che il cambiamento nella comunità è spesso accelerato dall'azione individuale, ci dice Dale S. Wright. Vimalakirti capisce in modo viscerale che qualsiasi conquista del singolo individuo è la risultante di un processo molto più articolato e di lunga durata, che comprende la storia passata di tutta la società, e che ci fa capire, come le realizzazioni dei singoli individui sono in realtà il prodotto di uno sforzo collettivo che va ben al di là dell'individuo, mettendo in luce, una volta di più, l'aspetto non dualistico del mondo più ampio. Vimalakīrti trova un equilibrio tra i suoi sforzi diretti al raggiungimento dei suoi obiettivi e la gratitudine di un'appartenenza ad un qualcosa che va ben al di là dell'io, ovvero un cosmo infinitamente più grande, ovvero una realtà che si estende nello spazio e nel tempo e in cui ogni creatura e ogni fenomeno è collegato a tutto il resto.

Dale S. Wright ci dice che la non dualità insegnata da Vimalakīrti è la consapevolezza delle nostre illimitate connessioni, un senso di essere circondati e supportati da forze che stanno tutt'intorno a noi e vanno ben al di là di noi. Queste intuizioni suscitano un sentimento di gratitudine per il dono della nostra stessa esistenza e un'umiltà che riconosce la nostra umile posizione nell'infinitamente più vasto ambito della realtà. Secondo Dale S. Wright, è questa visione non duale ciò che ispira il "fragoroso silenzio" di Vimalakīrti. Momentaneamente sollevato da ogni responsabilità, Vimalakīrti resta in silenzio, e sorride.

Ci potremmo aspettare che il Sūtra finisca qui, perché, cosa c'è da aggiungere al "fragoroso silenzio" di Vimalakīrti? Ma non è così. Il Sūtra prosegue con diversi altri capitoli. A questo punto, il narratore del Sūtra interviene per assicurarsi che i lettori abbiano afferrato il punto, affermando che

> Quando questi insegnamenti furono forniti, cinquemila bodhisattva varcarono la porta del Dharma della non dualità e raggiunsero la tolleranza (kṣānti) per la vacuità di tutte le cose.

Il Sūtra ci ricorda che le "dichiarazioni" dei bodhisattva forniscono trentadue risposte alla domanda

> esponetemi ciò che è, per i bodhisattva, l'entrata nella dottrina della non dualità,

anche se l'affermazione di Vimalakirti -- ovvero, il suo silenzio -- è stata la risposta più pregnante. Con l'evoluzione del buddismo nel corso dei secoli, il "fragoroso silenzio" di Vimalakīrti è cresciuto sempre più forte. I maestri di varie tradizioni lo hanno invocato come affermazione fondamentale per le loro interpretazioni del Dharma, proprio come ha fatto Vimalakīrti, per esempio il buddhismo Zen.

Il silenzio svolge un ruolo cruciale nel Dharma; questa è una componente significativa dell'eredità di Vimalakīrti: il silenzio ci fornisce un avvertimento sui pericoli dell'attaccamento ai dogmi del buddismo; ricorda ai praticanti che il dogmatismo e l'ego possono ricomparire quando meno ce lo aspettiamo.

## Considerazioni conclusive {.unnumbered}

L'autore del Vimalakīrti Sūtra, così come lo sanno i maestri Zen che praticano il silenzio, sapeva che è meglio non tacere del silenzio. L'autore del Sūtra si rende conto che il silenzio può svolgere la sua opera di liberazione solo in stretta relazione con il linguaggio del Dharma. Capisce che la separazione dualistica tra linguaggio e silenzio è una trappola, un'illusione non migliore di qualsiasi altro dualismo: scegliere una parte e rifiutare l'altra non può far altro che aggravare l'illusione. Così, il silenzio, proprio come il "non attaccamento" e il "lasciar andare", può svolgere la sua funzione liberatrice soltanto in connessione con il linguaggio del Risveglio. L'autore del Vimalakīrti Sūtra ci dice che "l'eloquenza di Vimalakīrti" -- ovvero, la sua fluidità nell'esporre il Dharma -- è così intrecciata con il pensiero non duale (l'equanimità non verbale) che l'una non può esistere senza l'altro. Secondo Dale S. Wright, la comprensione (mai esplicitamente descritta) di Vimalakīrti, a proposito di cosa sia la non dualità, può essere descritta facendo riferimento al profondo equilibrio che deve esistere tra la parola del Dharma, da una parte, e il silenzio, dall'altra.

Strumento principe per sviluppare una consapevolezza non dualistica è la meditazione. In particolare, la meditazione tibetana può essere considerata come una forma di "contemplazione decostruttiva". Tale pratica di contemplazione, infatti, consente la trasformazione dei materiali di cui è costituito il sé in qualcosa di nuovo. Nelle sue forme più radicali, tale forma di meditazione cerca addirittura di interrompere o di distruggere la struttura del sé per ristrutturare, dopo questa fase di decostruzione, gli schemi cognitivi che conferiscono coerenza al sé, creando una nuova struttura della mente.

Nella meditazione tibetana, l'assorbimento meditativo dissolve la struttura bipartita soggetto/oggetto, di un sé che osserva e degli oggetti (corpo, emozioni) che vengono osservati. L'attenzione non si concentra più su un oggetto particolare, ma solo sui puri aspetti qualitativi dell'esperienza cosciente. La consapevolezza che risulta da tale pratica è molto lontana da qualsiasi caratteristica normale del sé che sperimentiamo abitualmente nella vita quotidiana, e ha le caratteristiche di una consapevolezza non dualistica.

Mentre coltiva la "chiarezza" e la "stabilità" della mente, la meditazione buddhista cerca, nel contempo, di ridurre al minimo la presenza del sé, de-costruendo sistematicamente il senso di agenzia del sé, in modo tale da indebolire la struttura centralizzata e dualista che sostiene l'individualità. La meditazione buddista mira dunque a stabilire un senso di "non sé", che non è "un'entità cosciente" nel modo in cui normalmente intendiamo questo termine, ma invece promuove processi di coscienza che, indebolendo la struttura del "sé" e il senso di agenzia personale, consentono il sorgere di un pensiero non discorsivo. Nella meditazione, combinando contenuti razionali con l'attenzione selettiva, si trasforma la portata emotiva con cui elaboriamo i prodotti della nostra esperienza, e si altera la nostra concettualizzazione dei mondi interno ed esterno, ovvero, la struttura dualistica del pensiero.

<!-- Mediante l'attenzione selettiva, si realizza un disimpegno dalle strutture cognitive che usiamo normalmente per reinterpretare i dati che costituiscono la nostra identità così da potere ricostruire un diversa "persona" sulla base di nuovi schemi mentali. Il fine, dunque, è quello di "ri-costruire" creativamente il sé. -->
