# Kṣānti

Śāntideva, così come tutti gli altri pensatori della tradizione buddista, propone molte strategie per tenere la mente sotto controllo e per eliminare i kleśa (offuscazioni mentali).

::: callout-note
I kleśa, nel buddismo, sono stati mentali che offuscano la mente e si manifestano in azioni malsane. I kleśa includono stati mentali come ansia, paura, rabbia, gelosia, desiderio, depressione, ecc. Il termine kleśa viene tradotto come: afflizioni, contaminazioni, emozioni distruttive, emozioni disturbanti, emozioni negative, veleni mentali, nevrosi ecc. Nelle tradizioni buddiste, i tre kleśa di ignoranza, attaccamento e avversione sono identificati come la fonte di tutti gli altri kleśa. Nel Mahayana sono indicati come i *tre veleni*.
:::

Tali strategie seguono la logica degli "antidoti": la tolleranza è l'antidoto alla rabbia; il vigore è l'antidoto alla pigrizia; il disgusto per il corpo è l'antidoto alla lussuria. In questo capitolo ci occuperemo di kṣānti. Abbiamo già incontrato kṣānti quando abbiamo discusso il Vimalakīrti Sūtra. In quel contesto, kṣānti indicava

> la tolleranza intuitiva dell'incomprensibilità ultima e della natura non-nata di tutte le cose

cioè, indicava la tolleranza alla realizzazione della vacuità, ovvero la capacità di accettare con fiducia e in maniera gioiosa l'esperienza dell'assenza di fondamento, dell'impermanenza e dell'assenza di sé. Ma kṣānti è anche la terza delle sei perfezioni, ovvero delle pratiche che fanno maturare la mente del bodhisattva. Kṣānti è anche tradotta come "pazienza". A kṣānti è dedicato il sesto capitolo del Bodhicaryāvatāra e il nono capitolo dell'Antologia (Siksà-samuccaya) di Śāntideva. In ciò che segue fornirò un riassunto di ciò che viene descritto nel Siksà-samuccaya.

## La perfezione della pazienza

Nel nono capitolo del Siksà-samuccaya, Śāntideva si occupa di kṣānti quale antidoto al terzo veleno, ovvero all'avversione (odio o rabbia). Śāntideva scrive:

> per liberarti dalle catene delle distorsioni karmiche, devi fare uno sforzo per eliminare le emozioni reattive. Sin dall'inizio, resisti con pazienza.

> Coloro che non hanno studiato non conoscono né i metodi per sviluppare un'attenzione stabile, né i metodi per eliminare le emozioni reattive. Pertanto, instancabilmente cerca l'apprendimento \[del Dharma\].

> Ma anche se sei ben informato, se la tua condotta è contaminata \[dai kleśa\] sarà difficile sviluppare un'attenzione stabile. Perciò, dimora in solitudine.

> Chi ha un'attenzione stabile riceve come compenso l'eliminazione delle emozioni reattive. Per questa ragione, medita sull'impurità \[del corpo\].

::: callout-note
La meditazione sull'impurità (Skt. aśubha-bhāvanā) è una classe di tecniche volte a minare il desiderio sessuale riflettendo e visualizzando sulle impurità associate al corpo.
:::

Queste, ci dice Śāntideva, sono le istruzioni per eliminare le emozioni reattive.

Segue poi una serie di citazioni da vari Sūtra.

Nel Ugraparipṛcchā Sūtra si afferma:

> Il ... bodhisattva ... dovrebbe rimanere libero dall'attaccamento e dalla rabbia e dovrebbe mostrarsi indifferente alle otto preoccupazioni mondane. Se ottiene beni, moglie o figli, ricchezza, grano o proprietà, non deve diventare pomposo o euforico. Se non ottiene nessuno di questi, non deve dimostrarsi scoraggiato o depresso. Dovrebbe invece riflettere così: 'Tutte le cose condizionate sono illusorie e hanno la caratteristica di essere delle costruzioni mentali. Pertanto, i genitori, i figli, la moglie, la servitù, ... i dipendenti, gli amici, i compagni, i parenti e i membri della famiglia sono tutti manifestazioni delle evoluzioni del karma. Non sono miei e io non sono loro.'

Śāntideva si chiede come sia possibile evitare di rimanere vittime dell'infelicità. A tale domanda risponde:

> Evita di avere una mente debole!

Nell'Ugraparipṛcchā Sūtra si dice:

> ... per distruggere tutte le emozioni reattive, sviluppa una mente che è difficile da sconfiggere; per non cadere preda dell'attaccamento, sviluppa mente che non può essere conquistata, una mente che non trema quando si confronta con la moltitudine degli esseri malevoli.

La pratica è il mezzo per ottenere questo risultato:

> Nulla è difficile da ottenere con la ripetizione della pratica. Se con la ripetizione della pratica anche i più ignoranti \[...\] evitano di venire sopraffatti dalla fatica, quanto più questo è vero se consideriamo quel lavoro i cui risultati corrispondono alla felicità dell'esistenza ciclica, alla felicità del bodhisattva e allo stadio più alto dell'assorbimento meditativo!

> Mediante la ripetizione ti puoi convincere che la sofferenza degli altri ti renderà felice; ma allo stesso modo, generando abitualmente pensieri felici verso tutto ciò che causa sofferenza, puoi apprendere a dimorare in uno stato mentale felice. Questa pratica produce, quale risultato, lo stadio di assorbimento meditativo che è descritto nel Sutra dell'incontro del padre e del figlio:

> Nell'assorbimento meditativo chiamato "Tutto è colmo di felicità" i bodhisattva provano solo sentimenti positivi verso tutto ciò di cui sono consapevoli, evitando qualunque sentimento di sofferenza o infelicità. Anche se provano le pene dell'inferno, pensano solo pensieri felici. Anche se subiscono tutte le sofferenze possibili della condizione umana -- come farsi tagliare le mani, i piedi o il naso -- pensano solo pensieri felici. Anche se vengono picchiati con dei bastoni o delle fruste, pensano solo pensieri felici. Anche se vengono gettati in prigione... o se vengono ustionati dall'olio bollente, o se vengono dati alle fiamme come una lampada a olio, pensano solo pensieri felici. Anche se vengono offerti alla bocca di un demone o alla bocca di un leone ... o se vengono tagliati a pezzi ... o se vengono schiacciati dagli elefanti, pensano solo pensieri felici. Se gli vengono strappate le ossa, o se vengono impalati sui pali, o se vengno rapiti per essere uccisi, o se gli viene tagliata la testa, pensano solo pensieri felici; mai pensieri di sofferenza, né pensieri che non siano né felici né di sofferenza.

> Perché questo? Tali bodhisattva, grandi esseri, hanno svolto questa pratica per molto tempo dopo aver pronunciato il seguente voto:

> A tutti coloro che vogliono distruggermi, auguro di ottenere la felicità e la pace della tranquillità. A tutti coloro che possono proteggermi, trattarmi con rispetto, prendermi come loro maestro spirituale, onorarmi o farmi delle offerte, auguro di ottenere la felicità della tranquillità. E inoltre, a tutti coloro che mi maledicono, mi trattano male, mi picchiano, mi feriscono o in qualsiasi modo mi tolgono la vita, auguro di raggiungere la felicità del pieno Risveglio. Possano tutti risvegliarsi nel più alto, genuino e completo Risveglio.

> I bodhisattva, con questi pensieri, con queste azioni, con questo voto, augurano in ogni occasione la felicità a tutti gli esseri senzienti. I bodhisattva esprimono spesso questo desiderio, meditano su di esso e certano ripetutamente di metterlo in pratica. Come risultato di questo pensiero e di queste azioni, raggiungono l'assorbimento meditativo chiamato 'Tutto è colmo di felicità'. Nel momento in cui un bodhisattva raggiunge un tale assorbimento meditativo non può più essere distolto da esso e per sempre sfugge dalle azioni di Māra.

> Questo tipo di sforzo messo in atto dai bodhisattva fortifica tutte le forme di rinuncia, rafforza ogni azione che è difficile compiere, stabilizza ogni forma di paziente sopportazione, consolida la perseveranza e potenzia la stabilità meditativa e la saggezza. Pertanto, sii sempre essere gioioso.

L'Akṣayamati Sūtra afferma:

> Qual è la gioia più grande? È il piacere di ricordare le qualità del Buddha; la calma e la gioia d'animo; il non essere depressi; il non essere abbattuti; la libertà dal desiderio; la rinuncia alle delizie dei sensi; il provare piacere per il Dharma; la letizia della mente, l'agio del corpo; ... il non stancarsi mai di sentire parlare degli stati virtuosi; l'affidarsi agli insegnamenti che rivelano come stanno realmente le cose; ... l'avere sempre una mente libera dall'inimicizia; l'avere una forte motivazione; il cercare di sviluppare le qualità dei Buddha ... lo sforzo che ci allontana dalle Vie limitate; lo sforzo che ci allontana dall'avidità; il donare ai mendicanti; ... il deliziarsi della propria gentilezza verso coloro che sono immorali; la purezza della propria disciplina morale...; l'avere una mente che non si antagonizza di fronte all'inimicizia; il compiacersi della pazienza; la libertà dalla presunzione; la reverenza verso gli insegnanti spirituali; l'avere sempre una faccia sorridente; il non essere mai accigliato; la cortesia e la sincerità; l'assenza di ipocrisia; l'astenersi dall'adulazione; il non misurare i risultati raggiunti; avere aspirazioni pure; avere una mente senza durezza; ... la capacità di vedere il lato positivo di ogni cosa; la capacità di riconoscere la propria confusione; il non accusare gli altri dei loro limiti; il conformarsi alle regole del comportamento appropriato.

Il Mahā-megha Sutra fornisce una descrizione poetica, ci dice Śāntideva, dei bodhisattva che hanno raggiunto un alto grado di maturazione spirituale:

> \[Tali bodhisattva\] hanno la disciplina di coloro che sono sempre assorbiti dal pensiero di andare all'inferno. Amano andare all'inferno. Diventano gli esperti dell'andare all'inferno. Desiderano l'inferno, sono avidi dell'inferno e sono ben familiari con il pensiero del fuoco infernale.

Questo conclude la spiegazione della resistenza paziente e dell'accettazione del dolore.

Queste metafore così estreme si potrebbero descrivere dicendo che il bodhisattva prende molto sul serio l'idea che il saṃsāra è il ciclo della sofferenza -- e non può essere nient'altro, al di là dei brevi momenti in cui ci dimentichiamo di questo. In questo contesto, il bodhisattva manifesta gioia, perché rimanere nel saṃsāra è una sua scelta: ha scelto di rimanere nel saṃsāra per infiniti kalpa per contribuire alla salvezza degli esseri viventi. La sofferenza, in ogni istante, gli ricorda che la situazione in cui si trova è proprio la situazione che ha scelto di vivere. E di questo è felice.

Ma come il bodhisattva è in grado di mette in atto la sua paziente sopportazione? Śāntideva cita il Sāgaramati Sūtra:

> Un bodhisattva, grande essere, quando tormentato, scosso, disturbato, minacciato o picchiato dagli altri ... o da divinità controllate da energie demoniache, o dai messaggeri di Māra, non vacilla mai davanti al desiderio di potere giungere alla completa conoscenza della realtà o dall'essere motivato da intenzioni superiori. Non esita a sviluppare mahakaruṇā per tutti gli esseri senzienti. ... Non esita dall'applicarsi a non possedere nulla. Non esita dall'aiutare tutti gli esseri senzienti a maturare ed evita di aggrapparsi alla propria felicità. Coerentemente con una virtù superiore, sopporta un trattamento sprezzante da parte degli altri; sopporta la mancanza di rispetto e la critica; sopportare la rabbia degli altri, i rimproveri e le cattive parole. Sopporta le ferite che gli altri gli infliggono. Sopporta il peso dei fardelli di tutti gli esseri senzienti. Non si stanca, non si avvilisce, non si deprime, non si dispera. Mostra forza e perseveranza. È coraggioso, è in grado di compiere lo sforzo più grande e tiene sotto controllo le infatuazioni mentali. Quando gli altri si rivolgono duramente nei suoi confronti, non risponde in modo aspro. Quando viene colpito, non reagisce colpendo gli altri. Quando gli altri si arrabbiano con lui, non si arrabbia a sua volta. Quando viene rimproverato, non rimprovera gli altri a sua volta. In questo modo indossa l'armatura della contentezza interiore.

Il mio commento potrebbe essere quello di dire che il bodhisattva è più forte di qualsiasi avversità e utilizza le difficoltà della vita samsarica quali occasioni per procedere sulla via dello sviluppo spirituale. Essendo solo illusioni, miraggi, riflessi sull'acqua, schiuma che si dissolve in un momento, gli specifici dolori che proviamo e le specifiche malizie dirette verso di noi non devono essere presi troppo sul serio. Ci aspettiamo che tutto ciò succeda e tutte queste cose, in sé, non hanno alcun significato particolare: sono solo conseguenze di cause e condizioni che vengono da lontano. In un certo senso, in tutto questo "non c'è nulla di personale". È meglio non dare ad esso troppa importanza, per dirigere invece il nostro pensioro alla totalità, al dharmakāya che ha tutte le qualità positive che si possono immaginare (e anche, soprattutto, quelle che non siamo in grado di immaginare), alla bellezza della rete di Indra, piuttosto che focalizzarci su un qualche specifico aspetto della totalità che, incidentalmente, troviamo sgradevole e che, comunque, è marginale, ma deve stare lì.

Śāntideva continua con un'altra citazione:

> Rinunciare al corpo, non avere riguardo per il proprio corpo: questa è la perfezione della generosità. Quando il proprio corpo viene fatto a pezzi, \[i bodhisattva\] estendono la loro gentilezza amorevole a tutti gli esseri senzienti, senza lasciarsi trattenere dal dolore: questa è la perfezione della disciplina morale. Quando il loro corpo viene fatto a pezzi, \[i bodhisattva\] sopportano pazientemente tutto questo allo scopo di liberare coloro che li stanno ferendo, senza ferirli neppure nell'immaginazione: questa è la perfezione della pazienza. La perseveranza con cui non rinunciano alla motivazione di una conoscenza completa, con cui sostengono la loro forza interiore, con cui sopportano l'esistenza ciclica del samsara e con cui intraprendono le azioni virtuose: questa è la perfezione della perseveranza. La qualità per cui, quando vengno feriti, si preoccunano solo del Risveglio e si rivolgono solo alla pace e alla tranquillità: questa è la perfezione di stabilità meditativa. La qualità per cui, quando i loro corpi vengono fatti a pezzi, \[i bodhisattva\] capiscono che il corpo è come qualsiasi altro oggetto, e tutti gli oggetti sono solo illusioni; capendo questo, \[i bodhisattva\] riflettono sulla natura illusoria del loro corpo e sull'impermanenza dell'essere, sulla sofferenza dell'essere, sull'assenza di qualsiasi sé nell'essere e sulla pace dell'essere: questa è la perfezione della saggezza.

Di nuovo, il mio commento è che, anziché rispondere in maniera "automatica" alle difficoltà -- una senzazione di bruciore mi fa male e io "sono" questo dolore -- il bodhisattva è in grado di trasformare le sue proprie esperienze, mutandole dalla forma di un riflesso cieco in un'esperienza che viene letta attraverso le lenti del Dharma. La perfezione di kṣānti consente la trasformazione "alchemica" della sofferenza nella gioia attraverso la pratica del Dharma. Anziché accettare i kleśa senza metterli in discussione, mediante le capacità maturate con la pratica meditativa, e avendo reso "malleabile" la propria mente, i bodhisattva trasformano le loro afflizioni mentali in base alla consapevolezza che tutto è śūnyatā. Se siamo in grado di realizzare in maniera autentica la vacuità, il dolore assume "un colore" diverso. Più tenue. Se crediamo a Śāntideva, esso sbiadisce fino a scomparire.

Concluderei mettendo in evidenza l'aspetto seguente: c'è una componente eroica nel bodhisattva. Il bodhisattva è un guerriero. Non ha timore della sofferenza perché, senza la sofferenza, non potrebbe esistere. L'assenza di sofferenza significa che non siamo più nel saṃsāra; e il bodhisattva può esistere solo nel saṃsāra. Più grande è la sofferenza, maggiore è la sua ragione d'essere. Per questo, il bodhisattva è la creatura più coraggiosa; il bodhisattva non prova paura. Ciò che per gli altri è motivo di paura, per il bodhisattva è una motivazione: maggiore il dolore, maggiore la motivazione. Nel Bodhicaryāvatāra il coraggio del bodhisattva è descritto nel modo seguente:

> Ci sono alcuni il cui coraggio aumenta\
> Alla vista del proprio sangue.\
> Mentre altri perdono tutte le loro forze e svengono\
> Quando vedono il sangue di un altro!\
> --- (BCA VI:17)\

Il dolore che prova il bodhisattva non fa altro che aumentare il suo coraggio.

<!-- ## La rabbia distrugge la pace e la virtù (versi 1-11) -->

<!-- Śāntideva inizia il capitolo sulla pazienza del Bodhicaryāvatāra spiegando l'enorme carattere distruttivo della rabbia. La rabbia è l'opposto della pazienza, quindi, per sviluppare la pazienza, dobbiamo prima conoscere gli svantaggi della rabbia e i vantaggi della pazienza. Quando comprendiamo questo, diventa facile diminuire ed eliminare i primi e sviluppare i secondi. -->

<!-- L'attaccamento è spesso descritto come come l'olio che filtra nel tessuto, perché è quasi impossibile separare la mente vittima dell'attaccamento dall'oggetto dell'attaccamento. Allo stesso modo, la rabbia è descritta come un fuoco, perché brucia completamente ogni buona qualità. La rabbia può distruggere tutto, e quindi viene spesso definita il carattere negativo più distruttivo della mente. La rabbia è l'esatto opposto di kṣānti. La rabbia è la mente che desidera danneggiare l'altro --- questa è la sua funzione --- mentre bodhicitta, l'intenzione altruistica di raggiungere l'illuminazione, è l'opposto. Pertanto, kṣānti è vitale per sviluppare bodhicitta. -->

<!-- > \[Un momento di\] cattiva volontà distrugge tutte le buone azioni,\ -->

<!-- > così come la generosità e il culto dei sugata,\ -->

<!-- > anche se uno li ha praticati\ -->

<!-- > per migliaia di cicli cosmici.\ -->

<!-- > --- (BCA VI:1) -->

<!-- Un kalpa è un intervallo di tempo che abbraccia i quattro periodi della vita di un universo: formazione, durata, distruzione e periodo di vacuità. Ciascuno di questi quattro stadi dura venti kalpa intermedi, e ottanta presi insieme sono indicati come un grande kalpa. Il Sutra dichiara che il merito di tutte le buone opere accumulate nel corso di mille di questi grandi kalpa -- la pratica della generosità verso gli esseri, il rifugiarsi nei Tre Gioielli (il Buddha o Sugata che "procede nella beatitudine", il sacro il Dharma e il Sangha) e il fare offerte, l'osservanza della disciplina e così via -- tutto viene infranto da un solo istante di rabbia. -->

<!-- > Non c'è male grande come l'odio,\ -->

<!-- > nessuna disciplina ascetica grande come la pazienza.\ -->

<!-- > Pertanto, coltiva attivamente la pazienza\ -->

<!-- > con tutti i mezzi possibili.\ -->

<!-- > --- (BCA VI:2) -->

<!-- Con la rabbia non può esserci pace. Non c'è ostacolo più grande della rabbia nel nostro viaggio sulla via dell'illuminazione. Per questo motivo, dobbiamo fare tutto il possibile per proteggere la nostra mente da questa negatività. Dobbiamo impegnarci ad osservare con attenzione la nostra mente e non permettere mai il sorgere della rabbia; dobbiamo fare questo con la stessa attenzione che utilizziamo quando stiamo camminando su uno stretto sentiero sul bordo di un precipizio. Perché nei due casi i deficit di attenzione sono tragici nello stesso modo. -->

<!-- > Finché la puntura dell'odio è nel tuo cuore,\ -->

<!-- > la tua mente non troverà riposo,\ -->

<!-- > né gioia né felicità,\ -->

<!-- > nè quiete né stabilità.\ -->

<!-- > --- (BCA VI:3) -->

<!-- Coloro che sono tormentati dalla rabbia (le cui menti sono irritate dai nemici e dalle altre persone) non conosceranno mai la beatitudine della concentrazione, uno stato di perfetta felicità mentale. Sarà impossibile per loro raggiungere la concentrazione della mente e non conosceranno né la gioia mentale né il benessere fisico, neppure di notte, perché il sonno li abbandonerà. -->

<!-- > Il malcontento sorge ogni volta che il nostro desiderio viene contraddetto\ -->

<!-- > o si verifica l'indesiderabile.\ -->

<!-- > Quando l'odio riceve il suo nutrimento dal malcontento,\ -->

<!-- > prende forza e mi distrugge.\ -->

<!-- > --- (BCA VI:7) -->

<!-- Tutto ciò che produce situazioni spiacevoli e indesiderate (come la perdita di beni) e tutto ciò che ostacola l'ottenimento di ciò che vogliamo (in termini di proprietà e benessere), tutto ciò produce uno stato di fastidio mentale, e questo è ciò di cui si alimentano la rabbia e l'odio. Come è il cibo fa crescere il corpo, così l'infelicità della mente provoca rabbia e risentimento. Ed è la rabbia che rovina ogni sorta di bontà mentale. Quindi è essenziale superare tali stati di infelicità, perché sono l'alimento di cui si nutre la rabbia. -->

<!-- > Nessuno desidera dolore, umiliazione,\ -->

<!-- > insulto e disonore per se stesso\ -->

<!-- > o per coloro che ama,\ -->

<!-- > eppure li desidera per i suoi nemici.\ -->

<!-- > --- (BCA VI:11) -->

<!-- Si dice che ci sono ventiquattro oggetti a cui applicare la pazienza: dodici cose che non vogliamo e dodici cose che ostacolano i nostri desideri. Ci sono quattro cose che non vogliamo né per noi stessi né per chi ci sta vicino. Questi sono (1) la sofferenza, (2) gli svantaggi che derivano da cose come la discriminazione, (3) l'aggressione verbale diretta, e (4) la distruzione della buona reputazione attraverso la diffusione di voci dannose. Se considerati dal punto di vista delle situazioni passate, presenti e future, questi ventiquattro oggetti costituiscono insieme settantadue cause di rabbia. Si dice che dovremmo coltivare la pazienza nei loro confronti; dovremmo essere in grado di accettare ciò che non vogliamo, e anche considerare il fatto dello stesso "volere" come un difetto. -->

<!-- ## Imparare ad accettare la sofferenza -->

<!-- > Con grande difficoltà non si riesce quasi mai a raggiungere la felicità,\ -->

<!-- > ma il dolore si ripresenta senza sforzo.\ -->

<!-- > Ma la liberazione \[si verifica\] solo passando attraverso il dolore.\ -->

<!-- > Pertanto, mantieni saldo il tuo spirito!\ -->

<!-- > --- (BCA VI:12)\ -->

<!-- Nel mondo samsararico, le cause della felicità sono poche e compaiono solo sporadicamente. D'altra parte, ci sono molte cause per i nostri dolori e non siamo in grado di impedire che essi accadano. Questa è la definizione stessa di samsara; e fintanto che vaghiamo in esso, le cause della sofferenza sono infinite e non abbiamo altra scelta che sottometterci ad esse. Per chi lo capisce, però, c'è un aspetto positivo nel dolore. Perché senza sofferenza, non ci sarà mai rinuncia, ovvero la determinazione a liberarci dai dolori del samsara. Al contrario, se soffriamo, sorgerà in noi un desiderio di libertà definitiva. Pertanto, rivolgendosi alla propria mente, Śāntideva dice a se stesso di resistere e di accettare pazientemente la sofferenza. Perché la sofferenza è uno stimolo potente che ci spinge a uscire dal samsara. Vedendo quanto sia pervasiva la sofferenza, non c'è altro da fare che accettarla e, se possiamo, usarla per rinunciare a tutto il samsara. Senza sofferenza non ci può essere rinuncia alla sofferenza e quindi nessuna liberazione dalla sofferenza e nessuna illuminazione. Quando sorge la sofferenza, non c'è motivo di essere sorpresi: siamo nel samsara e non possiamo aspettarci nient'altro che la sofferenza. -->

<!-- ### Come accettare la sofferenza -->

<!-- > Non c'è niente che rimanga difficile dopo l'apprendimento,\ -->

<!-- > quindi, se si pratica prima\ -->

<!-- > con afflizioni meno gravi,\ -->

<!-- > anche i più grandi tormenti diventeranno sopportabili.\ -->

<!-- > --- (BCA VI:14)\ -->

<!-- Se una cosa è facile o difficile dipende solo da quanto la conosciamo. Tutto dipende dall'allenamento. Pertanto Śāntideva si dice che accettando piccoli disagi ora saremo in grado di sopportare difficoltà più grandi in futuro. -->
