# Advayajñāna e mahākaruṇā {#sec-non-dualism}

Advayajñāna, in sanscrito, significa "conoscenza non duale" e si riferisce a una conoscenza che ha trasceso la distinzione soggetto/oggetto che governa tutti gli stati convenzionali di coscienza sensoriale, generando un tipo di consapevolezza che è in grado di rimanere cosciente senza più richiedere un oggetto della coscienza.

Leggendo il Bodhicaryāvatāra di Śāntideva, abbiamo visto come la motivazione "ontologica" della Grande Compassione è l'idea che non vi è una separazione tra gli esseri: essendo privi di natura intrinseca, essendo "śūnya", gli esseri non possono essere "divisi", ovvero separati gli uni dagli altri. Essendo saṃskāra (esseri condizionati), possono essere concepiti solo come relativi, come in relazione gli uni con gli altri, ovvero come parti di una totalità.

In tali condizioni, nella meditazione del Vimalakīrti Sūtra, il modo corretto di rapportarsi al mondo è attraverso una consapevolezza non duale, advayajñāna. Un titolo alternativo per il Vimalakīrti Sūtra è *Il Sūtra sulla riconciliazione delle dualità*. Il Sūtra, infatti, descrive Vimalakīrti come colui che è in grado di giungere ad una conciliazione dei diversi aspetti del mondo. Ma la riconciliazione delle dualità, o differenze, non è la loro cancellazione. Vimalakīrti non si acquieta nella visione dell'unità indifferenziata di tutte le cose. Vimalakīrti vede come tutte le cose si relazionano per formare la totalità, pur rimanendo distinte l'una dall'altra. Vede con grande chiarezza la differenza tra ricchi e poveri, e lavora per cambiare una tale differenza. Vede la differenza tra chi soffre in modo orribile e chi no, la differenza tra chi affronta le difficoltà con abilità e compostezza e chi non lo fa. Tutte queste differenze rimangono valide: il non-dualismo di Vimalakīrti non è una forma di monismo.

Questo per dire che il mondo in cui vive Vimalakīrti rimane un mondo complesso, disordinato, confuso e in rapido cambiamento, proprio come il nostro mondo. Vimalakīrti non aspira ad un mondo senza differenze, senza tensioni o conflitti; un tale mondo. infatti, sarebbe privo di vita. Mediante la sua pratica, invece, Vimalakīrti fa sorgere in sé l'interesse per questa complessità, un interesse che lo porta a volere essere consapevole di cosa realmente stia accadendo, mantenendo nel contempo la sua motivazione (vīryapāramitā: "l'entusiasmo di compiere atti virtuosi") e la sua pazienza (kṣāntipāramitā).

Vimalakīrti è raffigurato come qualcuno che non si innervosisce e perde l'equilibrio quando le tensioni aumentano o quando punti di vista diversi si sfidano a vicenda. Sembra aver superato il disagio che tutti noi proviamo in situazioni tese e complicate. Ha coltivato compostezza, flessibilità e resilienza e fa appello a queste capacità per dare equilibrio e speranza agli altri. Il suo non dualismo è una visione operante, una comprensione esperta del tutto che non è limitata dalla paura e non intende escludere nessuno.

A cosa si deve questa compostezza? Che cosa fornisce a Vimalakīrti un supporto o un sostegno sufficiente per consentirgli un intervento così abile nella vita quotidiana? La risposta del Sutra è che un tale fondamento corrisponde ad un modo di pensare non duale. Una visione che accetta l'opposizione e il conflitto come dimensioni essenziali della realtà in cui viviamo. Percepire le differenze e tensioni come il tessuto stesso della realtà consente di sviluppare un atteggiamento di equanimità che rende possibile un sapiente lavoro di mediazione. Rendersi conto di come e perché cose molto diverse sono in realtà unite è ciò che rende possibile lavorare efficacemente con loro.

Nel Sutra, Vimalakīrti chiede ai bodhisattva: "cos'è la non dualità?". Ognuno di loro fornisce una risposta molto profonda.

> Quando penso 'io' e 'mio', questa è dualità. Quando 'io' e 'mio' vengono a mancare, questa è non dualità.\

> Dove c'è contaminazione e purificazione, questa è dualità. Quando si va oltre la contaminazione e la purificazione, questa è non dualità.\

> Dove ci sono atti virtuosi e non virtuosi, questa è dualità. Quando si va oltre il virtuoso e il non virtuoso, questa è non dualità.\

> Se pensi che questa sia solo la realtà mondana e che esista un altro mondo più sublime, questa è dualità. Quando vai oltre il mondano e il sublime, questa è non dualità.\

Gli esempi diventano sempre più elaborati e includono spiegazioni relative a tutti i Sei Pāramitā.

> Produzione e distruzione sono due, ma ciò che non è prodotto e non accade non può essere distrutto. Così il raggiungimento della tolleranza (kṣānti) della non-nascita delle cose è l'ingresso nella non dualità.\

::: callout-note
Ricordiamo, come abbiamo visto in precedenza, che

> \[i bodhisattva\] raggiungono la tolleranza intuitiva dell'incomprensibilità ultima e della natura non-nata di tutte le cose.
:::

Inoltre:

> Se desideri la liberazione perché non ti piace il saṃsāra, questa è dualità. L'unico modo in cui puoi realizzare la non dualità è andare oltre il desiderio della liberazione e l'antipatia per il saṃsāra.

Dopo una lunga lista di spiegazioni di cosa sia la non-dualità fornita da 32 bodhisattva si arriva a Mañjuśrī, quale rivolge la sfida al loro ospite, e il capitolo giunge al suo completamento in quello che è stato a lungo chiamato il "fragoroso silenzio" di Vimalakīrti. Evocando la non dualità mediante il rifiuto di fare alcuna distinzione -- né un'affermazione né una negazione -- Vimalakīrti fornisce una delle più note affermazioni del Dharma nella storia buddista.

Nel nono capitolo di *Living skillfully*, Dale S. Wright cerca di articolare in qualche modo il "fragoroso silenzio" di Vimalakīrti. Dale S. Wright ci dice che, mentre la maggior parte di noi lotta con il conflitto tra la tranquillità della nostra pratica meditativa e la nostra esperienza nella vita quotidiana, Vimalakīrti sperimenta insieme queste due esperienze, indagando la loro non dualità. Vede che la trasformazione personale è resa possibile dal cambiamento storico collettivo e che il cambiamento nella comunità è spesso accelerato dall'azione individuale, ci dice Dale S. Wright. Vimalakirti capisce in modo viscerale che qualsiasi conquista del singolo individuo è la risultante di un processo molto più articolato e di lunga durata, che comprende la storia passata di tutta la società, e che ci fa capire, come le realizzazioni dei singoli individui sono in realtà il prodotto di uno sforzo collettivo che va ben al di là dell'individuo, mettendo in luce, una volta di più, l'aspetto non dualistico del mondo più ampio. Vimalakīrti trova un equilibrio tra i suoi sforzi diretti al raggiungimento dei suoi obiettivi e la gratitudine di un'appartenenza ad un qualcosa che va ben al di là dell'io, ovvero un cosmo infinitamente più grande, ovvero una realtà che si estende nello spazio e nel tempo e in cui ogni creatura e ogni fenomeno è collegato a tutto il resto.

Dale S. Wright ci dice che la non dualità insegnata da Vimalakīrti è la consapevolezza delle nostre illimitate connessioni, un senso di essere circondati e supportati da forze che stanno tutt'intorno a noi e vanno ben al di là di noi. Queste intuizioni suscitano un sentimento di gratitudine per il dono della nostra stessa esistenza e un'umiltà che riconosce la nostra umile posizione nell'infinitamente più vasto ambito della realtà. Secondo Dale S. Wright, è questa visione non duale ciò che ispira il "fragoroso silenzio" di Vimalakīrti. Momentaneamente sollevato da ogni responsabilità, Vimalakīrti resta in silenzio, e sorride.

Ci potremmo aspettare che il Sutra finisca qui, perché, cosa c'è da aggiungere al "fragoroso silenzio" di Vimalakīrti? Ma non è così. Il Sutra prosegue con diversi altri capitoli. A questo punto, il narratore del Sutra interviene per assicurarsi che i lettori abbiano afferrato il punto, affermando che

> quando questi insegnamenti furono dichiarati, cinquemila bodhisattva entrarono nella porta della non dualità del Dharma e raggiunsero la tolleranza (kṣānti) per la vacuità di tutte le cose.

Il sutra ci ricorda che le "dichiarazioni" dei bodhisattva forniscono trentadue risposte alla domanda

> esponetemi ciò che è, per i bodhisattva, l'entrata nella dottrina della non dualità,

anche se l'affermazione di Vimalakirti -- ovvero, il suo silenzio -- è stata la risposta più pregnante. Con l'evoluzione del buddismo nel corso dei secoli, il "fragoroso silenzio" di Vimalakīrti è cresciuto sempre più forte. I maestri di varie tradizioni lo hanno invocato come affermazione fondamentale per le loro interpretazioni del Dharma, proprio come ha fatto Vimalakīrti, per esempio il buddhismo Zen.

Il silenzio svolge un ruolo cruciale nel Dharma; questa è una componente significativa dell'eredità di Vimalakīrti: il silenzio ci fornisce un avvertimento sui pericoli dell'attaccamento ai dogmi del buddismo; ricorda ai praticanti che il dogmatismo e l'ego possono ricomparire quando meno ce lo aspettiamo.

Ma l'autore del sutra, come i maestri Zen che praticano il silenzio, sapeva che è meglio non tacere del silenzio. L'autore del sutra si rende conto che il silenzio può svolgere la sua opera liberatrice solo in stretta relazione con il linguaggio del Dharma. Capisce che la separazione dualistica tra linguaggio e silenzio è una trappola, un'illusione non migliore di qualsiasi altro dualismo: scegliere una parte e rifiutare l'altra può solo aggravare l'illusione. Così, il silenzio, proprio come il "non attaccamento" e il "lasciar andare", può svolgere la sua funzione liberatrice soltanto in connessione con il linguaggio del risveglio. L'autore del sutra si rende conto che ciò che viene chiamato "l'eloquenza di Vimalakīrti" -- ovvero, la sua fluidità nell'esporre il Dharma -- è così intrecciata con l'equanimità non verbale, che l'una non può esistere senza l'altra. Secondo Dale S. Wright, il delicato equilibrio tra la parola del Dharma e il silenzio è il segreto della non dualità di Vimalakīrti.
