# Il significato di secolarizzazione

## Introduzione

Nei precedenti capitoli abbiamo confrontato la tradizionale buddista e le pratiche secolarizzate di coltivazione della compassione. Abbiamo analizzato i fondamenti filosofici e psicologici sottostanti ai due approcci. Questo confronto ha rivelato una convergenza nell'idea di un potenziale naturale e innato negli esseri umani, ma anche una divergenza nella concettualizzazione delle forme avanzate di compassione. Mentre i pensatori buddisti hanno sviluppato schemi elaborati per distinguere i livelli ordinari e avanzati di compassione, il contesto secolarizzato si limita a quelli che, nella tradizione buddista, sono i livelli iniziali della compassione.

Abbiamo poi esaminato i due approcci pedagogici incorporati nelle due culture della compassione.

-   La cultura della compassione buddista Mahāyāna è definita dalla cosmologia buddista, una filosofia morale basata sul karma, e dalla didattica del percorso di perfezionamento spirituale del bodhisattva.
-   La cultura della compassione secolare è fondata su una visione scientifica dei fenomeni, su una ricerca progettata per lo sviluppo della salute individuale e, in una certa misura, su un senso etico secolare rivolto alla promozione della pace.

Il confronto delle due pedagogie della coltivazione della compassione si è concentrato sulla tecnica contemplativa del tonglen. Dalle prime scritture Mahāyāna fino alla letteratura commentata tibetana del XIV e XV secolo, questa tradizione rivela uno slancio creativo e innovativo che ha trasformato un'impegnativa meditazione dei bodhisattva avanzati in una contemplazione accessibile anche ai praticanti principianti. La tradizione tibetana ha trasformato la coltivazione della compassione che richiede la comprensione dei concetti di anātman e śūnyatā in una meditazione molto più accessibile che può essere praticata senza la necessità della decostruzione del pensiero dualistico. In questo senso, le trasformazioni tibetane del modo di intendere la compassione hanno aperto la strada alle pratiche secolarizzate occidentali.

Coerentemente con questa idea, abbiamo visto che la pedagogia CCT è infusa di idee buddiste in ogni fase del suo programma. Tuttavia, è anche chiaro che la formazione secolarizzata si distingue dalla didattica buddista in quanto enfatizza uno sviluppo personale, che non mette in discussione l'ambiente in cui si trova l'individuo, ed è molto meno ambiziosa nel suo obiettivo. Al contrario, la coltivazione della compassione buddista fa parte del sentiero del bodhisattva che conduce al completo risveglio, e non può essere concepita come un obiettivo autonomo che può essere raggiunto all'interno della sua vita sociale e lavorativa dell'individuo.

Ciò che resta da esplorare sono questioni fondamentali riguardanti le implicazioni del processo di secolarizzazione delle pratiche buddiste tradizionali per un pubblico nell'Europa e nel Nord America del ventunesimo secolo.

## The consequence of secularizing Buddhist compassion training

Discussions about the meaning of the secularization have multiplied in recent years. Charles Taylor's *A Secular Age* describes three types of secularity, namely

1.  the expulsion of religion from the sphere of public life, that is, from the economic, political, cultural, educational, professional, recreational spheres of activity;
2.  secondly, the decline of religious belief and practice,
3.  thirdly the understanding of the belief in God as a free personal choice, "one human possibility among others".

Particularly the third variant illustrates the situation in which secular compassion training has arisen. In CCT, religious belief is optional; the program is designed to be compatible with all religious affiliations, as well as atheism and agnosticism.

"Secular" in the context of compassion training refers not to an exclusion or rejection of religion, but to an all-inclusive attitude towards religion. This all-inclusive stance is precisely the model of secularism that the Dalai Lama sees as the foundation of his secular ethics.

Religious belief is not excluded in CCT but relegated to the private sphere of the individual, as compassion is associated with a naturalistic worldview based on rationality and scientific empiricism rather than religious or moral obligation.

The motivation of secularizing compassion training did not emerge from a disenchantment with religion, but rather from the wish to make the training available for the largest possible audience.

The comparative analysis of CCT with Buddhist antecedents has shown that, while using secular language,

-   CCT does indeed express a worldview that is strongly influenced by Buddhist thought,
-   the IM communicates in large part Buddhist didactic methods without using Buddhist terminology (except for the term tonglen).

Secularizing Buddhist compassion cultivation in the case of CCT thus refers to the result of two processes.

-   The first is the removal of Buddhist terminology and Buddhist concepts so that the compassion training may not conflict to currently accepted scientific ideas, while keeping intact as much as possible the didactic methods developed in Buddhist traditions.
-   The second process is that of hybridizing: The training elements derived from sources other than Buddhism such as the psychotherapeutic and dyadic exercises, or the training in self-compassion, are inserted for the purpose of making the training "workable" for Western audiences.

## Evaluating the Secularization of Buddhist Contemplative Practices

Two critiques have been directed to the secularization of Buddhist contemplative practices.

First, the first critique concerns the fact that the Buddhist practices are built on different models of mental health than those pursued by Western audiences.

::: callout-note
It is especially important to keep in mind this point when evaluating the effectiveness of the secularizated Buddhist contemplative practices.
:::

Let us take the example of mental distress and depression. Early Buddhist sūtras depict suffering as an *inevitable* ingredient of being alive. They posite that

> the only genuine remedy to suffering is escape from saṃsāra (the phenomenal world) altogether, and escape requires, among other things, abandoning hope that happiness in this world is possible.

This type of hopelessness, which in Buddhism represents a state of *spiritual maturity*, is regarded as a form of depression in present day culture of the West.

Our contemporary culture prefers to see spiritual practice as a "science of happiness."

Buddhist thinkers such as Śāntideva acknowledge that suffering can serve as a catalyst for spiritual practice. Therefore, Buddhist contemplative practice *does not aim at soothing short-term suffering* when this pain serves eradicating the causes for long-term suffering.

Western models of mental health however tend to see distress and depression as undesirable mental states that must be remedied.

Secular compassion training, therefore, is vulnerable to the criticism that it runs the risk of being used to pacify short-term forms of suffering instead of being used as catalysts for a more profound transformation.

A second critique argues that secular programs are the product of a selective appropriation and commodification of Buddhist contemplative practices for the sole purpose of satisfying the widespread consumerism of Western societies: a watered-down version of mindfulness, \[...\] a meditation for the masses, stripped of its essential ingredients, prepackaged and neatly stocked on the shelves of the commercial self-help supermarkets". Commodifying Buddhist ideas for self-centred purposes entails tailoring them for the individualistic consumer orientation of Western capitalist societies instead of eradicating egocentrism, the basic root of suffering.

### Response to the Critiques

To these critiques one could answer that CCT has no claim to authenticity in a Buddhist sense of transmission, and that its validity comes from the fact that "it works."

The critique of selective appropriation with the purpose of commodification is the one that is more difficult to answer. However, we should note that the most important agent in such secularization project is the Dalai Lama himself. He has financially contributed to the Stanford program, regularly participates in conferences, and has, over the years, developed his secular ethics, with which he promotes compassion as a human, not a religious quality.

Moreover, it is also clear that the history of Buddhist thought shows the presence of very dramatic changes. Changes form Theravada Buddhism to Mahayana Buddhism are very extreme. In today's discussion, we have seen the transformation from the advanced bodhisattva practice of equalizing and exchange (as described by Śāntideva in the late 7th to mid-8th century CE) to the way in which the practice of tonglen can be applied by novices' in the Lojong and Lamrim contemplations.

Thus, the commodificaiton is only one aspect of this phenomenon. The other being the progressive transformation of Buddhist practice throughout the centuries and its ability to adapt to the needs of its host culture.

Finally, there is an inevitable transformation of religious concept when a religion starts a dialogue with science. In the present context, compassion becomes natural, psychological category, a universal quality of every human being, at the core of human nature, rather than an ethical imperative.
