project:
  type: book
  output-dir: docs
  
book:
  title: "Training cognitivo e contemplativo per lo sviluppo della compassione"
  author: "Corrado Caudek"
  # cover-image: images/cover.png
  # site-url: https://rstudio-education.github.io/hopr/
  # repo-url: https://github.com/jjallaire/hopr/
  # repo-branch: master
  # repo-actions: [edit]
  # sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    # - preface.qmd
    - 01-intro.qmd
    - 02-definitions.qmd
    - 03-nature_nurture.qmd
    - 04-what_is_trained.qmd
    - 05-how_is_trained.qmd
    - 06-tonglen.qmd
    - 07-wisdom.qmd
    - 08-living_skillfully.qmd
    - 09-patience.qmd
    - 10-tibetan_traditions.qmd
    - 11-meditation.qmd
    - 12-secularism_1.qmd
    - 13-secularism_2.qmd
    - 14-gilbert.qmd
    - 15-kirby.qmd
    - 16-measurement.qmd
format:
  html: 
    theme: 
      - cosmo
      - r4ds.scss
    # cover-image: cover.png
    code-link: true
    callout-appearance: simple
  pdf:
    toc: true
    number-sections: true
    colorlinks: true



