project:
  type: book
  output-dir: docs
  
book:
  title: "Training cognitivo e contemplativo per lo sviluppo della compassione"
  author: "Corrado Caudek"
  # cover-image: images/thomas-laird-10.jpeg
  # site-url: https://rstudio-education.github.io/hopr/
  # repo-url: https://github.com/jjallaire/hopr/
  # repo-branch: master
  # repo-actions: [edit]
  # sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    # - preface.qmd
    - 01-intro.qmd
    - 02-definitions.qmd
    - part: tradition.qmd
      chapters:
      - 03-nature_nurture.qmd
      - 04-what_is_trained.qmd
      - 05-how_is_trained.qmd
      - 06-tonglen.qmd
      - 07-wisdom.qmd
      - 08-living_skillfully.qmd
      - 09-patience.qmd
      - 10-meditation.qmd
      - 11-non_dualism.qmd
      - 12-upaya.qmd
      - 13-tibetan_traditions.qmd
      - 14-secularism_1.qmd
      - 15-secularism_2.qmd
    - part: secular_programs.qmd
      chapters:
      - 16-gilbert.qmd
      - 17-kirby.qmd
      - 18-measurement.qmd
  appendices:
    - a1-meditation.qmd
format:
  html: 
    theme: 
      - cosmo
      - r4ds.scss
    # cover-image: thomas-laird-10.jpeg
    code-link: true
    callout-appearance: simple
  pdf:
    toc: true
    number-sections: true
    colorlinks: true



