project:
  type: book
  output-dir: docs
  
book:
  title: "Training cognitivo e contemplativo per lo sviluppo della compassione"
  author: "Corrado Caudek"
  # cover-image: images/thomas-laird-10.jpeg
  # site-url: https://rstudio-education.github.io/hopr/
  # repo-url: https://github.com/jjallaire/hopr/
  # repo-branch: master
  # repo-actions: [edit]
  # sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    # - preface.qmd
    - 01-intro.qmd
    - 02-definitions.qmd
    - part: tradition.qmd
      chapters:
      - 03-nature_nurture.qmd
      - 04-what_is_trained.qmd
      - 05-how_is_trained.qmd
      - 06-meditation.qmd
      - 07-tonglen.qmd
      - 08-wisdom.qmd
      - 09-non_dualism.qmd
      - 10-nagarjuna.qmd
      - 11-living_skillfully.qmd
      - 12-patience.qmd
      - 13-upaya.qmd
      - 14-tibetan_traditions.qmd
      - 15-secularism_1.qmd
      - 16-secularism_2.qmd
    - part: secular_programs.qmd
      chapters:
      - 17-gilbert.qmd
      - 18-kirby.qmd
      - 19-measurement.qmd
  appendices:
    - a1-meditation.qmd

bibliography: compassion.bib
csl: apa.csl

format:
  html: 
    theme: 
      - cosmo
      - r4ds.scss
    callout-appearance: 
      - simple
    code-link: true
    link-citations: yes
    code-fold: true
    code-tools: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true