# Descrizioni della pratica della mediatazione {#sec-appendix-meditation}

Forniamo qui alcuni accenni relativi alla pratica della meditazione.

## Ānāpānasati-sutta

Iniziamo con l'Ānāpānasati-sutta, il "Discorso sulla consapevolezza del respiro", il quale offre un'esposizione dettagliata sulla meditazione. È uno dei Sutra più antichi su questo tema. Bhikkhu Anālayo (2015) riassume l'Ānāpānasati-sutta evidenziando 16 passi nella pratica della meditazione del respiro. Questi 16 passi sono suddivisi in 4 tetradi.

### Prima tetrade

> Sempre consapevole egli inspira, consapevole egli espira.\
> 1. Inspirando a lungo, egli comprende: 'io inspiro a lungo'; od espirando a lungo, egli comprende: 'io espiro a lungo.'\
> 2. Inspirando brevemente, egli comprende: 'io inspiro brevemente'; od espirando brevemente egli comprende: 'io espiro brevemente.'\
> 3. Egli si addestra in questo modo: 'inspirerò facendo esperienza dell'intero corpo'; egli si addestra in questo modo: 'espirerò facendo esperienza dell'intero corpo'.\
> 4. Egli si addestra in questo modo: 'inspirerò placando le formazioni corporee.'; egli si addestra in questo modo: 'espirerò placando le formazioni corporee.'

Praticamente, questo significa che, inizialmente, dopo essere diventato consapevole del proprio respiro, il meditatore diventa consapevole della lunghezza dei respiri. Questi possono essere lunghi o corti. L'enfasi è sulla mera osservazione, non vi è alcun tentativo di controllare il respiro. Il passo successivo è di diventare consapevole 'dell'intero corpo'. Questo può essere inteso come diventare consapevole dell'intero corpo del respiro, ovvero essere in grado di distinguere tra la sua parte iniziale, centrale e finale. Oppure, può essere inteso come diventare consapevole dell'intero suo corpo nella posizione seduta. In questa interpretazione, il terzo passo nella progressione comporterebbe un cosciente ampliamento del campo della consapevolezza dal solo respiro all'intero corpo del meditatore. Infine, calmare il respiro porta naturalmente ad una maggiore tranquillità generale del corpo, e la tranquillità del corpo a sua volta aumenta la calma del processo del respiro. Quindi sembra naturale interpretare il quarto stadio come una richiesta di calmare il respiro e il corpo.

### Seconda tetrade

> 5.  Egli si addestra in questo modo: 'io inspirerò facendo esperienza della gioia'; egli si addestra in questo modo: 'io espirerò facendo esperienza della gioia.'\
> 6.  Egli si addestra in questo modo: 'io inspirerò facendo esperienza della beatitudine'; egli si addestra in questo modo: 'io espirerò facendo esperienza della beatitudine';\
> 7.  Egli si addestra in questo modo: 'io inspirerò facendo esperienza delle formazioni mentali'; egli si addestra in questo modo: 'io espirerò facendo esperienza delle formazioni mentali.'\
> 8.  Egli si addestra in questo modo: 'io inspirerò placando le formazioni mentali'; egli si addestra in questo modo: 'io espirerò placando le formazioni mentali.'\

<!-- Da un punto di vista pratico, il grado di base di calma fisica e mentale stabilito attraverso i quattro passi precedenti conduce, in questa seconda fase, al sorgere di una forma di gioia (passo 5). I praticanti possono anche incoraggiare consapevolmente il sorgere della gioia riesaminando la condizione piacevole di tranquillità che si sperimenta dopo aver proceduto in tutte le fasi della prima tetrade. La gioia, che a volte può anche essere piuttosto esuberante ed estatica, conduce all'esperienza più calma della felicità (passo 6), nel senso di una condizione di corpo e mente piacevolmente soddisfatta. Con il passo (7), la consapevolezza della gioia e della felicità porta alla consapevolezza di qualsiasi altra formazione mentale o attività presente nella mente. Questo e il passo successivo di questa tetrade sono simili agli ultimi due passi della tetrade precedente, poiché in entrambi i casi la meditazione procede dalla consapevolezza delle formazioni corporee o mentali ad uno stadio in cui esse si calmano (passo 8). È quando si raggiunge uno stato mentale di distacco dalle formazioni corporee e mentali (saṃskāra) che queste si calmano. Nel contesto attuale, ciò comporta, in particolare, la volontà di abbandonare anche gli saṃskāra di gioia e felicità. -->

<!-- Intesi in questo modo, i passi (5) e (6) mostrano chiaramente che la gioia e la felicità sane hanno un ruolo centrale nella pratica e dovrebbero essere incoraggiate. Allo stesso tempo, tuttavia, i passi (7) e (8) mostrano che la gioia e la felicità devono essere vissute con un atteggiamento disposto a lasciarle andare, consentendo loro di placarsi naturalmente una volta giunto il momento. -->

Un modo per implementare praticamente la seconda tetrade della presenza mentale del respiro può quindi essere quello di procedere dalla gioia che deriva dal calmare i processi corporei all'esperienza più quieta della felicità la quale, attraverso la presa di coscienza di qualsiasi altra attività mentale che ha luogo in quel momento, porta al quietarsi di tutte le attività mentali. I temi principali di tale pratica sono quindi quelli che assegnano un posto importante alla gioia e alla felicità, come parti integranti della pratica, le quali però vengono abbandonate per raggiungere l'obiettivo di calmare tutti i processi mentali.

### Terza tetrade

> 9.  Egli si addestra in questo modo: 'io inspirerò facendo esperienza della mente'; egli si addestra in questo modo: 'io espirerò facendo esperienza della mente.'\
> 10. Egli si addestra in questo modo: 'io inspirerò rasserenando la mente'; egli si addestra in questo modo: 'io espirerò rasserenando la mente.'\
> 11. Egli si addestra in questo modo: 'io inspirerò concentrando la mente'; egli si addestra in questo modo: 'io espirerò concentrando la mente.'\
> 12. Egli si addestra in questo modo: 'io inspirerò liberando la mente'; egli si addestra in questo modo: 'io espirerò liberando la mente.'\

La meditazione passa dall'essere consapevoli dei contenuti della mente al diventare consapevoli della mente stessa. <!-- Finora, il progresso della pratica ha comportato un passaggio dalla consapevolezza del corpo (o di aspetti del corpo) con la prima tetrade all'esperienza delle attività o delle qualità mentali (come gioia e felicità) con la seconda tetrade. Il passaggio alla terza tetrade comporta un ulteriore grado di raffinamento. Diventare consapevoli della mente in quanto tale, nel senso di riconoscere ciò che è consapevole del respiro o consapevole della gioia e della felicità, richiede un certo grado di esperienza meditativa e familiarità con l'introspezione. --> In termini pratici, passare dalla fase (8) alla fase (9) può avvenire attraverso un ripiegamento su se stessa della consapevolezza, per così dire. Dall'essere consapevoli del respiro, si diventa consapevoli di chi è consapevole del respiro. Dall'essere consapevoli dell'esperienza di gioia e felicità, si dirige poi la consapevolezza verso l'agente di tale consapevolezza.

La consapevolezza della mente stessa porta naturalmente al sorgere della letizia, poiché questo ripiegamento su se stesso, o verso l'interno della consapevolezza, si traduce in un tipo di esperienza molto più sottile e calmo. Il tipo di letizia che sorge in questa fase della pratica è quello che porta facilmente alla concentrazione, alla mente che diventa raccolta in sé e unificata (passaggio 11). In questo modo, la mente diventa sempre più libera da qualsiasi ostruzione o impedimento mentale. Essendo diventata naturalmente concentrata, al momento attuale, la mente è anche libera da qualsiasi interferenza da parte del meditatore, per quanto sottile possa essere. La libertà di questa calma compostezza è ciò di cui il praticante è consapevole (passo 12), insieme al ritmo in costante cambiamento di inspirazione ed espirazione. Quindi un modo per implementare in pratica la terza tetrade della presenza mentale del respiro sarebbe quello di esaminare dall'esterno l'atto di esaminare (ovvero, la consapevolezza); procedere poi dalla letizia che deriva da un tale stato alla liberazione della mente da qualsiasi distrazione o interferenza.

### La quarta tetrade

> 13. Egli si addestra in questo modo: 'io inspirerò contemplando l'impermanenza'; egli si addestra in questo modo: 'io espirerò contemplando l'impermanenza.'\
> 14. Egli si addestra in questo modo: 'io inspirerò contemplando lo svanire'; egli si addestra in questo modo: 'io espirerò contemplando lo svanire.'\
> 15. Egli si addestra in questo modo: 'io inspirerò contemplando la cessazione'; egli si addestra in questo modo: 'io espirerò contemplando la cessazione.'\
> 16. Egli si addestra in questo modo: 'io inspirerò contemplando il lasciare andare'; egli si addestra in questo modo: 'io espirerò contemplando il lasciare andare.'\

<!-- Con il primo di questi passi, l'impermanenza, che comunque era presente sullo sfondo della pratica durante tutti i passi precedenti, ora si sposta al centro dell'attenzione: non è solo la natura impermanente del respiro, ma piuttosto la natura impermanente di tutti gli aspetti dell'esperienza a diventare l'oggetto della contemplazione. Ciò include la natura impermanente della gioia e della felicità, così come la natura impermanente dell'agente della conoscenza, ovvero la mente. Anche se la capacità di conoscere è una costante in tutte le esperienze della mente, il fatto stesso di essere in grado di conoscere cose diverse rende chiaro che anche la mente deve cambiare se stessa. Se fosse permanente, ovvero sempre uguale a se stessa, sarebbe per sempre congelato nella condizione di conoscere una cosa soltanto. -->

<!-- Da un pieno apprezzamento dell'impermanenza, la pratica passa poi al virāga, che potrebbe essere tradotto come "svanire" oppure come "distacco" (passo 14). Entrambe le traduzioni fanno emergere delle sfumature correlate di ciò che, nell'esperienza reale, sono aspetti strettamente interconnessi nel progresso dell'insignt. Rendersi conto che tutto cambia ed è destinato a svanire suscita in noi il distacco: diventiamo naturalmente disincantati e disillusi da ciò che inevitabilmente è impermanente e svanirà. In questo modo la emozioni che abbiamo associato agli eventi si indeboliscono fino a svanire. Tale distacco, che deriva dal rendersi conto che tutti i fenomeni sono impermanenti, rendendo inequivocabilmente chiaro che il mondo del samsare è incapace di fornirci una soddisfazione duratura -- ovvero ci rende consapevoli del fatto che il samsara produce necessariamente duḥkha. Tutti i fenomeni condizionati producono "insoddisfazione" e questo insight determina un coinvolgimento sempre minore e rafforza la libertà interiore attraverso il distacco. -->

<!-- Dal distacco, le istruzioni nell'Ānāpānasati-sutta procedono alla cessazione (nirodha). Per cessazione si può intendere il fatto di prestare attenzione all'aspetto della scomparsa di tutto ciò che viene sperimentato. Sia questo il respiro o la gioia, o qualunque altra cosa si esperisca nel momento presente, tutto è destinato a cessare, lasciando spazio al sorgere di qualcos'altro. Contemplare la cessazione acuisce la comprensione dell'impermanenza, portando in primo piano l'aspetto più estremo dell'impermanenza: le cose sono destinate a venire a mancare. Un altro aspetto complementare della pratica è quello che ci fa rendere conto che il distacco (passo 14) porta gradualmente alla cessazione di duḥkha. Mentre la cessazione finale di duḥkha richiede il pieno risveglio, tutti noi possiamo fare esperienza della cessazione di alcuni desideri e forme di attaccamento. -->

<!-- Tanto più il praticante riesce ad accettare il carattere inevitabile della cessazione (passo 15), ovvero, ad accettare che le cose finiscano, più facile diventa l'esperienza del lasciar andare (passo 16). Lasciare andare, o rinunciare, qui si riferisce all'esperienza di lasciar andare qualsiasi forma di attaccamento, lasciare andare ogni senso di appropriazione delle esperienze nei termini di "io" o "mio". -->

Un modo per implementare praticamente la quarta tetrade della consapevolezza del respiro, come descritto nell'Ānāpānasati-sutta, è quello di procedere dall'appercezione della natura mutevole del respiro alla consapevolezza della natura impermanente di qualunque aspetto dell'esperienza. La consapevolezza dell'impermanenza diventa il fondamento dell'esperienza del distacco, il che conduce alla consapevolezza della cessazione di ogni cosa, per finire con il riconoscimento che dobbiamo "lasciar andare", nel modo più completo possibile, tutto ciò che esperiamo. Il tema principale dell'attuazione delle istruzioni per l'ultima tetrade della consapevolezza del respiro è dunque la coltivazione dell'insight basato sulla consapevolezza dell'impermanenza.

## Laṅkāvatāra Sūtra

Un'altra descrizione molto nota è quella fornita dal Laṅkāvatāra Sūtra (350-400 CE). Si notino le somiglianze con le quattro tetradi dell'Ānāpānasati-sutta.

1.  Nel primo stadio, il meditatore esamina i dharma materiali, "gli oggetti esterni", si chiede: "Essi sono forse diversi dalla coscienza? Oppure, sono la coscienza stessa che così si manifesta come nello stato di sogno?" Se li percepisce come oggetti esterni, dovrà scomporli nelle loro componenti, nelle loro condizioni e nelle loro cause, fintanto che non sorgerà in lui il seguente pensiero: "Tutto \[l'universo\] è unicamente pensiero; non esiste più una realtà esterna."
2.  Nel secondo stadio, avendo così meditato sui dharma materiali, ci si rivolge ai dharma immateriali. Il Laṅkāvatāra Sūtra ci dice che, essendo stata dissolta nell'analisi meditativa la realtà materiale, ciò fa anche venire meno l'esistenza di un "soggetto percettore", "in quanto il percettore dipende dal percepibile". Perciò il pensiero "privo di percepibile e percettore" diventa non-duale, "risiede nel supporto della Tathata", "passa oltre" il percettore e il percepito, e permane nella conoscenza senza l'apparenza della dualità.
3.  Nel terzo stadio, il meditatore "passato oltre il solo-pensiero", "passa oltre" anche a questa stessa conoscenza, quella senza apparenza di dualità. Ovvero, il meditatore medita in questo modo: "Poiché è illogico che le cose possano nascere per opera propria o in virtù di altro e data la falsità di realtà percepita e di soggetto percettore, è logicamente insostenibile che anche la conoscenza non-duale possa essere veramente reale, poiché è inseparata da essi".
4.  Nel quarto stadio, il meditatore abbandona ogni forma di attaccamento e si "stabilisce" nella comprensione dell'assenza di natura propria di tutti i dharma. Colui che vi risiede, penetrando nella verità suprema, entra nel samādhi privo di rappresentazioni concettuali.

## Kamalaśīla

Un'altra descrizione della pratica della meditazione che ha avuto un grande eco nella tradizione tibetata è quella fornita da Kamalaśīla (c. 740-795), monaco buddista dell'università di Nālandā, nella sua opera *La progressione della mediatazione II*. I testi di Kamalaśīla sono stati citati per più di un millennio in Tibet fino ad essere discussi ai giorni nostri, ad esempio, nell'opera *Tesoro della conoscenza* di Jamgön Kongtrül (1813--1899), e in tanti altri commentari più recenti dell'opera di Jamgön Kongtrül. *La progressione della mediatazione* è disponibile, in italiano, nel testo *La rivelazione del Buddha* a cura di Raniero Gnoli (un allievo di Giuseppe Tucci). La traduzione de *La progressione della mediatazione II* è anche disponibile, accompagnata da un commento del Dalai Lama, nel testo *Stages of meditation*.

<!-- Nell'ottavo secolo, Śāntarakṣita (725--788) si recò in Tibet per insegnare le fasi della meditazione. Śāntarakṣita, il cui nome si traduce in italiano come "protetto da Colui che è in pace", fu un importante e influente filosofo buddista indiano, in particolare per la tradizione buddista tibetana. Śāntarakṣita fu un filosofo della scuola Madhyamaka, studiò nel monastero di Nālandā e divenne il fondatore di Samye, il primo monastero buddista del Tibet. Quando si rese conto di essere vicino alla morte, disse: "Ho impartito questi insegnamenti. In futuro potrebbero verificarsi problemi e le cose potrebbero andare storte. Se ciò accadrà, invitate il mio allievo Kamalaśīla dall'India. Sarà in grado di spiegare chiaramente la meditazione e rimuovere eventuali errori di interpretazione che potrebbero sorgere". Questo fu il suo ultimo desiderio, poi morì. -->

<!-- Esaminiamo di seguito alcuni brani tratti da *La progressione della mediatazione I* di Kamalaśīla (c. 740-795), anche lui un monaco buddista dell'università di Nālandā. Gli scritti di Kamalaśīla hanno avuto una grande risonanza nella tradizione tibetana e sono stati citati per più di un millennio fino, ad esempio, in volume molto noto dedicato alla meditazione dell'opera *Tesoro della conoscenza* di Jamgön Kongtrül (1813--1899). -->

<!-- La descrizione della pratica della meditazione è fornita ne *La progressione della mediatazione II*, tradotto ne *La rivelazione del Buddha*, pp.  -->

<!-- > Per il meditatore che dimora in questo samādhi, in virtù della cessazione di tutte le costruzioni concettuali, sia l'ostacolo delle afflizioni, sia l'ostacolo dei conoscibili sono interamente dissolti. -->

<!-- > Infatti, nel venerabile Satyadvayanirdesa \[Sutra\] e in altre opere, il Buddha ha spiegato che la radice, la causa, dell'ostacolo delle afflizioni è la concezione erronea secondo cui cose che in realtà sono non-sorte, non-distrutte e inesistenti sarebbero esistenti e via dicendo. Ed è in virtù dell'abbandono di tutte le costruzioni concettuali sull'esistenza, la non-esistenza, ecc., il quale deriva da questo esercizio continuato dello yoga, che si verifica l'abbandono di ogni concezione erronea come l'esistenza, ecc., che ha come sua propria natura la nescienza e che è la radice dell'ostacolo delle afflizioni. Perciò, distruggendone la radice, egli abbandona completamente l'ostacolo delle afflizioni. E così è detto nel Satyadvayanirdesa: O Mañjuśrī, come vengono rimosse le afflizioni? Mañjuśrī disse: Poiché dal punto di vista assoluto tutti i Dharma sono assolutamente non-nati, non-sorti, non-esistenti, è dalla verità convenzionale che deriva la concezione erronea dell'inesistenza. Ed in base a questa concezione erronea che si verifica un'operazione mentale discorsiva; e in base a tale operazione mentale discorsiva, c'è la riflessione scorretta; in conseguenza della riflessione scorretta c'è l'attribuzione di un io a realtà in sé prive di io; in seguito all'attribuzione di un io, c'è il sorgere dei punti di vista errati; infine, dal sorgere dei punti di vista errati si producono le afflizioni. O Devaputra chi, invece, in base alla realtà assoluta conosce tutti i Dharma come assolutamente non-nati, non-sorti, non-esistenti, è, secondo tale realtà, privo di errore. E chi in base alla realtà assoluta è privo di errore, è privo di costruzioni concettuali; e chi è privo di costruzioni concettuali è perfettamente concentrato; e per chi è perfettamente concentrato non sorge l'attribuzione di un io, fino a che, secondo la vera realtà, non c'è il sorgere neppure del punto di vista del nirvana. Per chi dimora in tal modo nella non-produzione, le afflizioni devono considerarsi completamente rimosse. Egli è detto "privo delle afflizioni". Devaputra, quando per mezzo di una conoscenza priva di apparenze egli conosce secondo realtà assoluta le afflizioni come assolutamente vuote, assolutamente inesistenti, assolutamente impermanenti, allora, Devaputra le afflizioni sono perfettamente comprese. In verità, Devaputra, come chi conosce l'origine di un serpente velenoso ne rende inoffensivo il veleno, esattamente allo stesso modo, Devaputra, per colui che conosce l'origine delle afflizioni, le afflizioni stesse si estinguono. -->
