# Le secolarizzazione della compassione {#sec-secular-programs .unnumbered}

L'addestramento alla compassione secolare è un fenomeno culturale in rapida espansione, che segue i programmi, leggermente più vecchi, della riduzione dello stress basata sulla mindfulness (Jon Kabat-Zinn, 1990). Il fine dei programmi secolarizzati di coltivazione della compassione è quello di promuovere e migliorare il valore pedagogico e l'applicabilità della formazione alla compassione per il pubblico contemporaneo. Questa seconda parte del testo fornisce maggiori informazioni sul significato e la portata della coltivazione della compassione dal punto di vista della ricerca scientifica in questo campo, ampliando così la nostra comprensione di questo fenomeno culturale. Man mano che la coltivazione della compassione cresce in influenza, non solo la conoscenza delle sue radici filosofiche e storiche, ma anche i risultati delle ricerche scientifiche, consentono di sostenere un dialogo fruttuoso tra studiosi buddisti, scienziati, operatori sanitari, e "appassionati di compassione" che partecipano a programmi secolari in generale.

<!-- Man mano che la coltivazione della compassione cresce in influenza, la conoscenza delle sue radici filosofiche e storiche, l'ampiezza dei suoi metodi e obiettivi didattici e le sue somiglianze e divergenze negli adattamenti secolari consente di sostenere un dialogo fruttuoso tra studiosi buddisti, scienziati, operatori sanitari, e "appassionati di compassione" che partecipano a programmi secolari in generale.  -->
