# Mezzi espedienti {#sec-upaya}

Il pensiero del risveglio che guida la vita di Vimalakīrti è centrato su due ideali buddisti, saggezza (prajñā) e compassione (karuṇā). In tutto il Sūtra, ci viene mostrato come questi due ideali si fondono. Vimalakīrti dice, ad esempio, che

> la meditazione sulla vacuità si consuma efficacemente nello sviluppo di tutti gli esseri viventi.

Vale a dire che, in ultima analisi, la saggezza della vacuità si realizza -- "si consuma" -- nel compiere atti compassionevoli nella vita reale. Ma una parola chiave in questa citazione è "efficacemente". Una saggia comprensione della natura "vuota" della realtà, e un impegno a estendere la compassione a tutti gli esseri viventi, sono ideali che si applicano a tutto, sempre. Per chiunque sia motivato da questi ideali, però, la domanda di come essi possano essere applicati nella vita concreta, nei modi più efficaci, è una domanda cruciale. Deve essere stato chiaro per i primi buddisti, così come lo è per noi, che le persone più compassionevoli, e che possiedono la più completa saggezza, non sono necessariamente le persone più abili nell'esprimere quella saggezza e quella compassione in un'azione efficace. Infatti, se il Dharma è una medicina per sanare la sofferenza umana, è importante capire come somministrare al meglio la cura poiché, come tutti sappiamo, una medicina somministrata nel modo sbagliato, o al momento sbagliato, può avere effetti opposti a quelli desiderati.

Portare la saggezza e la compassione nela vita quotidiana sembra richiedere un qualche tipo di abilità. I buddisti Mahayana chiamavano questa abilità upāya (a volte tradotto "abilità nei mezzi,"mezzi abili", "mezzi espedienti" o "abilità salvifica"). Questa abilità, upāya, è in primo piano nel Vimalakīrti Sūtra. Sebbene l'articolazione della saggezza (prajñā) della vacuità (śūnyatā) sia molto più centrale nell'insegnamento di Vimalakīrti, la presentazione di questi concetti non è particolarmente innovativa poiché si allinea strettamente con i Sūtra della Perfezione della Saggezza. L'innovazione di Vimalakirti consiste nell'estensione della saggezza della vacuità ai mezzi salvifici (upāya), così che la realizzazione della vacuità possa essere applicata in un'ampia gamma di contesti concreti: upāya è il lato creativo del Dharma.

L'abilità di upāya è la capacità di far sì che le azioni svolte nella vita quotidiana vengano motivate dalle intuizioni che derivano dalla realizzazione della vacuità. È la capacità di applicare, nel modo più efficace, i più alti valori buddisti di saggezza e compassione alle condizioni sempre mutevoli della vita reale. Pertanto, una delle prime cose che il Sūtra ci dice su Vimalakīrti è che "ha integrato" śūnyatā e upāya. Questo è il modo con il quale il Sūtra dice che non è sufficiente realizzare la vacuità nella meditazione, è invece necessario sapere applicare una tale realizzazione nel mondo reale, il quale è costituito da circostanze imprevedibili e difficili da affrontare.

L'enfasi buddista relativa alla necessitò di impegnarsi nella vita di questo mondo, piuttosto che all'aspirazione di un mondo celeste al di là di questo, porta in primo piano la questione della saggezza pratica. Il Sūtra raffigura Vimalakīrti che lavora nelle scuole, che è coinvolto nel dibattito politico, che è pienamente impegnato ovunque interessi divergenti e seri disaccordi possono portare a conflitti. L'upāya di Vimalakīrti si manifesta ovunque sia necessaria una calma presenza e un'efficace riconciliazione. In questi contesti, il successo richiede la capacità di lavorare con energia e con flessibilità per gli altri, senza limitarsi solamente a portare avanti i propri interessi personali.

Per essere efficaci in questi contesti, i bodhisattva devono essere disposti a "sporcarsi le mani". Quindi vediamo Vimalakirti nelle strade a lavorare con persone di ogni possibile estrazione e temperamento, senza cercare di evitare le difficoltà che avrebbe incontrato lì, ma proprio a causa di esse. Si immerge volutamente nel mondo dei guai e della sofferenza, senza remore. Il sentiero buddista non offre formule dettagliate su come rispondere al meglio alle difficoltà della vita reale. Nessuno, nemmeno Vimalakīrti conosce in anticipo la strategia che è opportuno impiegare, né sa come andranno a finire le cose, come conseguenza delle scelte fatte. Nessuno può evitare l'ambiguità e l'incertezza nella vita, nessuno riesce a evitare i rischi. Nemmeno Vimalakīrti L'abilità dei "mezzi salvifici" viene appresa attraverso tentativi ed errori. La volontà di fallire e la capacità di imparare dal fallimento sono precondizioni essenziali per lo sviluppo di qualsiasi abilità. Il Sūtra afferma:

> La saggezza non integrata con upāya è schiavitù, ma la saggezza integrata con upāya è la liberazione.

Questo tema è ripreso, in maniera molto simile, nella *Lampada sul Sentiero verso l'Illuminazione* di Atisha (982--1054):

> La saggezza priva di mezzi abili\
> E anche i mezzi abili privi di saggezza\
> Sono ciò che viene chiamato schiavitù.\
> Quindi, non abbandonare nessuno dei due.

Ricordiamo come l'autore del Sūtra faccia fingere a Vimalakirti di essere malato. Oppure Vimalakīrti è veramente malato, non lo sappiamo.

> Sono malato finché qualcuno è malato

dice Vimalakīrti. Il Buddha comprende lo stratagemma di Vimalakīrti -- la sua abilità nei mezzi espedienti -- e vuole mandare i suoi discepoli e i bodhisattva a far visita a Vimalakīrti, sapendo che, quando essi arriveranno da Vimalakīrti, lui sarà pronto a "svegliarli", esponendo ciascuno di loro a intuizioni che riguardano le loro particolari debolezze. Ma in risposta alla richiesta del Buddha, nessuno di questi abili praticanti buddisti è disposto ad andare a far visita a Vimalakīrti. Alla domanda, uno per uno declinano l'invito, ognuno raccontando la storia di un proprio precedente incontro personale con Vimalakīrti. In ogni caso confessano che l'intuizione del Dharma di Vimalakīrti era al di là della loro comprensione e che non potevano fare a meno di restare impressionati, sconcertati e imbarazzati dalla brillantezza dei suoi insegnamenti.

L'autore del Sūtra ci racconta molte storie per accentuare la profondità della saggezza di Vimalakīrti in contrasto con la rigidità monastica dei discepoli del Buddha. Vimalakīrti è un laico la cui realizzazione del Dharma è così profonda che i suoi insegnamenti confondono anche i discepoli più avanzati del Buddha.

Ma nel quinto capitolo il problema del Buddha viene risolto. Mañjuśrī, il bodhisattva della saggezza, accetta di andare a controllare la salute di Vimalakīrti. Il conseguente dialogo sul Dharma tra i due bodhisattva è brillante e gli eventi che accadono a casa di Vimalakīrti quel giorno sono descritti in dettaglio in cinque capitoli, il cuore del Sūtra.

Oltre alla disciplina della pratica, cosa è necessario per raggiungere il livello di eccellenza mostrata da Vimalakīrti? Il Sūtra ne sottolinea cinque capacità personali.

1.  *Umiltà o altruismo e senso di sé indebolito.* Il rapporto di Vimalakīrti con la gente comune di Vaiśālī è un riflesso della sua umiltà. Piuttosto che vantarsi della sua conoscenza superiore o della sua posizione aristocratica, Vimalakīrti mostra apprezzamento per i meriti degli altri e tratta tutti con profondo rispetto. Superando il suo senso di importanza personale, Vimalakīrti modella il suo vivere pienamente consapevole con la propria posizione infinitesimale nell'universo. Lungi dal dar luogo ad un atteggiamento timido volto all'annullamento di sé, la vera umiltà è il risultato di un disciplinato superamento del sé che suscita stupore e gratitudine. Quindi Vimalakīrti si impegna a vivere senza "nozioni possessive" e "senza afferrare", "libero dalle abitudini dell'"io" e del "mio". Si apre al mondo. Questo senso di sé onesto e non gonfiato fornisce la base per l'uso dei mezzi salvifici.
2.  *Affrontare i rischi con coraggio e saggezza.* L'uso dei mezzi salvifici richiede il coraggio di agire essendo consapevoli dei rischi coinvolti. Tutti dobbiamo affrontare le contingenze nella vita e, momento dopo momento, non possiamo evitare di esibire la nostra vulnerabilità. Non c'è modo di sfuggire al rischio del fallimento. Le minacce non possono essere controllate o eliminate, ma ciò che possiamo controllare è il modo in cui reagiamo ad esse. Quando le cose vanno male, reagire male è il pericolo più grande. Tra i modi in cui facciamo ulteriore danno a noi stessi quando sorgono difficoltà ci sono l'autoinganno, il risentimento, un senso di indignazione, la disperazione e la rassegnazione. Vivere abilmente richiede di sviluppare la capacità di non fare marcia indietro di fronte ai rischi della vita, sviluppando nel contempo la capacità di affrontare tali rischi in maniera saggia. Come ci ricorda Mañjuśrī: "Senza uscire nel grande oceano è impossibile trovare le perle preziose e inestimabili."
3.  *Equanimità: equilibrio e integrità.* Se il cambiamento e l'interdipendenza sono la vera natura della realtà, lo squilibrio e l'instabilità sono anch'essi elementi imprescindibili della vita. Affrontare queste forze distruttive accettandone l'inevitabilità, riuscendo, allo stesso tempo, a rigenerare equilibrio e integrità, è una delle maggiori sfide per una vita abile. L'equilibrio tra accettazione e resistenza richiede un profondo senso di equanimità. I bodhisattva, mediante il loro profondo senso di equanimità, diventano in grado di scegliere saggiamente piuttosto che di reagire in modo compulsivo. La vera equanimità non è indifferenza, distanza, insensibilità. Al contrario, i bodhisattva sono "responsabili di tutte le cose ma liberi da nozioni possessive". Con equanimità «abbandonano l'avidità e l'odio». Equanimità sta per uguaglianza: "È ciò che giova a sé e agli altri". Coltivando l'equanimità, i bodhisattva sono in grado di vivere con integrità, in uno stato di non conflitto interiore, nel quale i vari aspetti della vita sono tenuti in equilibrio.
4.  *Imparare mediante la consapevolezza.* La pratica continua rende l'individuo più esperto, ma la persona "esperta" non è solo qualcuno che ha avuto molte esperienza. È piuttosto qualcuno che ha vissuto le varie esperienze in modo consapevolmente, con l'intenzione di apprendere e di svilupparsi. "Mindfulness" qui vuol dire semplicemente prestare attenzione. È uno stato mentale intenzionale e focalizzato che è presente, cosciente e composto, in contrasto con uno stato mentale che è inconsapevole, reattivo e non focalizzato. Vimalakīrti afferma che una tale disciplina meditativa sviluppa "l'idoneità della mente" e che il bodhisattva è "equamente bilanciato tra attenzione e consapevolezza". Non è un attaccamento consapevole né un abbandono della responsabilità, ma un'apertura della mente che favorisce il superamento consapevole di sé a beneficio dell'intera comunità.
5.  *Flessibilità e improvvisazione.* L'abilità essenziale della flessibilità -- la capacità di adattarsi, improvvisare e riallinearsi alle circostanze mutevoli -- non è una capacità che tutti noi possediamo in maniera naturalmente. È qualcosa che va appreso, un prodotto di pratiche meditative di concentrazione e apertura che ci consentono di entrare in contatto diretto con il mondo che ci circonda. Risiedere in un stato di non dualità ci offre la possibilità di essere di rilassati, curiosi e in grado di sperimentare in un modo che evita la deliberazione estenuante basata sull'ansia. Vimalakīrti descrive questo stato dicendo che è uno stato privo delle esigenze della «possessività», «libero dalle abitudini di 'io' e 'mio'». In questa zona di agio e di libertà, è possibile agire ai margini della razionalità ordinaria. Improvvisando, Vimalakīrti si fida di istinti che sono stati affinati nella pratica meditativa e si comporta sentendosi davvero a casa propria nel mondo. Vimalakīrti agisce intuitivamente, senza esitazione. È come se fosse stato portato fuori di sé, avendo eliminato i segni di una goffa proprietà e di una cupa determinazione. Ha dissolto l'ansiosa preoccupazione per il sé. E sebbene queste abilità di "improvvisazione" siano state acquisite attraverso la disciplina pratica, la loro apparizione improvvisa continua a sorprenderci.

Queste sono alcune delle abilità dell'upāya di Vimalakirti. C'è un avvertimento generale, tuttavia, che è fondamentale tenere a mente. La capacità personale di agire è solo una piccola parte di un quadro ben più ampio: le culture in rapida evoluzione dell'umanità, e la trasformazione e la possibile distruzione del pianeta che ci ospita. La realtà è dominata da dimensioni che vanno ben oltre l'individuo, e neppure upāya può fare cambiare il corso di queste forze. Le nostre piccole azioni si svolgono all'interno di gigantesche correnti storiche e cosmologiche di impermanenza che hanno un effetto sulla nostra vita molto più grande di quanto qualsiasi nostra scelta potrà mai avere.

Con questo in mente, ecco il punto cruciale. Come individui, non siamo responsabili dell'esito della storia umana, dell'evoluzione della vita o del corso del cosmo più ampio. Ma siamo responsabili di ciò che accade nella piccola "nicchia ecologica" che abitiamo. Questa responsabilità è il nostro compito e quel compito può essere svolto in maniera abile o meno. In quel dominio, limitato, siamo pienamente responsabili. E in quel dominio, sviluppare una saggezza pratica fa la differenza. È fondamentale comprendere entrambe le prospettive e tenerle entrambe a mente. Primo, che ognuno di noi ha una vita individuale da condurre; questo è il nostro compito principale, la nostra responsabilità. E in secondo luogo, questa nostra vita individuale è immersa in una realtà più ampia che ci abbraccia e ci travolge. Sul primo di questi due aspetti, possiamo allacciarci le cinture e metterci al lavoro. Rispetto al secondo aspetto, non possiamo che "lasciare andare" e accettare tutto ciò che ci viene dato come un dono, con gratitudine, stupore e meraviglia.
